### ISSUE TITLE
[Enhancement] Calculate new plot distribution on storage

### ISSUE THREAD

**Issue by rcamarda390** [MrPig91/PSChiaPlotter#10]
when I have existing mixed capacity drives that have plots and then I buy a new larger hard disk, it would be great to have your tool  tell me which existing plots to move to the new storage to maximize storage.
It is like your current Get-chiakplotcombination -driveletter  g, but in reverse:
Based on what plots I have, tell me which ones to move to new storage to get best fit.
Thanks!

**Comment by MrPig91** [comment]
Unfortunately all my efforts are poured into the PSChiaplotter GUI. I like the idea but I currently do not have the time to add this feature. Thank you for the suggestion.
