### ISSUE TITLE
Dynamic disks errors

### ISSUE THREAD

**Issue by GeoWeb-Pro** [MrPig91/PSChiaPlotter#103]
![1](https://user-images.githubusercontent.com/66351529/122008445-f7302d80-cdb0-11eb-9473-3ac8691e2197.png)

Added job que with a dynamic disc created in disks manager, manually adding path, when job wanted to start this errors comes up.

**Comment by Jacek-ghub** [comment]
I got the same error when using RAID0 (that is also using dynamic disks, without an option to switch to basic).

**Comment by MrPig91** [comment]
This error came about when using Basic Plotting or by choosing a volume from the drop down in the advanced plotting?

**Comment by Jacek-ghub** [comment]
In my case, when using Basic Plotting, and targeting RAID0 array.  I think, it also happened when I tried to use \\host\path format in Basic Plotting.  There is more info about what I did in "Missing RAID arrays" thread.

**Comment by GeoWeb-Pro** [comment]
> This error came about when using Basic Plotting or by choosing a volume from the drop down in the advanced plotting?

Basic Plotting and targeting RAID0 array as Jacek-ghub said

**Comment by GeoWeb-Pro** [comment]
With the new update you can manual add in Basic Plotting
