### ISSUE TITLE
Phase 1 Concurrent Limiter Not Working

### ISSUE THREAD

**Issue by rathishsiva** [MrPig91/PSChiaPlotter#105]
Hi,

I am facing this issue where even if i am limiting the Phase 1 to max concurrent 1, once the first run passes Phase 1, all runs are released (ie. if 5 in overall queue, all 5 are released even with me limiting the Phase 1). 
In my example, i have 2 jobs, with both jobs with max 5 concurrent and limited to 1 run in phase 1. But as you can see, in the screenshot, once the the first runs complete phase 1, the rest of the runs are initiated (all phase 1 - even when i limit max 1 phase 1 for each job). 
![Phase1_limit](https://user-images.githubusercontent.com/85540840/122075651-d3aac880-ce2c-11eb-970f-61a116dbb61a.JPG)
![Phase1_Not_Restricted](https://user-images.githubusercontent.com/85540840/122075660-d5748c00-ce2c-11eb-816f-b4ecd199ab43.JPG)

**Comment by MrPig91** [comment]
I am really sorry about this. I had a poor implementation of this. I am reworking it hand having good results. Plan to release it tonight.

**Comment by rathishsiva** [comment]
No worries mate. Appreciate the good work! I understand that you are planning to incorporate madmax as well? That would be awesome! Looking forward!

**Comment by MrPig91** [comment]
I believe I have updated the code and it should work better now. Let me know if you run into any issues with the new update. I also added Check Plot button on the completed runs tab.
