### ISSUE TITLE
[Question] Enable Phase 1 Limit logic

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#108]
Hello,

Is there a place where  can read more about how "Enable Phase 1 Limit" is working?

Is it applied on all running Jobs or only within the current job?
How the "Delay (minutes)" will be affected by the "Enable Phase 1 Limit"?

Thank you very much for your time,

**Comment by MrPig91** [comment]
Currently the phase 1 limit will only apply to the given Job it was assigned. I have thought about adding a global phase 1 limit, but this has not been put into place.

The delay in minutes will delay the start of the first run of each queue. If you set the delay to 0 it will start each queue when phase 1 has an open slot based on the limit.

Does this answer you question?

**Comment by kszabok** [comment]
So with this setting won't phase 1 overlay?
![parallel](https://user-images.githubusercontent.com/84275629/122440946-594d8600-cf9d-11eb-9005-4ed339f3c3a5.png)

**Comment by kszabok** [comment]
So no Phase 1 overlay with this settings?
![parallel](https://user-images.githubusercontent.com/84275629/122445791-2ce83880-cfa2-11eb-9b89-68d81337f5fc.png)

**Comment by MrPig91** [comment]
It will only allow for one phase 1 at a time with those settings.

**Comment by spazhead13** [comment]
is phase 1 option available yet< i just updated and do not see it?

**Comment by MrPig91** [comment]
It is available, which version are you on @spazhead13 ? It is in the top of the new job window under the plots / parallel groupbox.

**Comment by spazhead13** [comment]
it doesn't show up for me?

<img width="650" alt="Screen Shot 2021-06-18 at 2 14 08 AM" src="https://user-images.githubusercontent.com/63839488/122515139-fe3a8400-cfda-11eb-90f4-af68e6e75dec.png">

i opened administration powershell typed " Update-Module -Name PSChiaPlotter" press "A" for all
and reopened "Show-PSChiaPlotter" still not there, how do i tell what versions i'm currently running?

**Comment by kszabok** [comment]
You can check version in main window summary section

**Comment by spazhead13** [comment]
Hi, i dont see this either??


<img width="953" alt="Screen Shot 2021-06-18 at 4 11 23 AM" src="https://user-images.githubusercontent.com/63839488/122529323-5bd6cc80-cfeb-11eb-9e52-0084c7094c25.png">

**Comment by GeoWeb-Pro** [comment]
After you run the command to update does it ask for permission (press Y to update) as that version you have is quite dated

**Comment by spazhead13** [comment]
yes it does, but i press "A" for all

**Comment by spazhead13** [comment]
do i have to close all powershell windows before i do the update?  cause all i did was close the plotter and leave the normal powershell window open and open an admin powershell window, then i do the update, but i still use the old normal powershell window to restart the plotter

**Comment by spazhead13** [comment]
i'll try again after the plots finish and this time i'll do a reboot of windows first, then update

**Comment by MrPig91** [comment]
Yes you will need to close out of the old powershell window and open a new one after doing the update. The old window will continue to use the module it first loaded into the session. You shouldn't need to restart your computer, but it is a good idea to restart your computer time to time, so no harm there.

**Comment by spazhead13** [comment]
thanks that fixed it!!  thanks for your help!
