### ISSUE TITLE
I really want to use your program, but can't, and I am a NOOB to powershell

### ISSUE THREAD

**Issue by BizWithBruce** [MrPig91/PSChiaPlotter#11]
![image](https://user-images.githubusercontent.com/83860716/117532039-ce648d80-afe5-11eb-8682-02eac7b34161.png)

**Comment by rcamarda390** [comment]
I tried it again (at time of this post) and I was able to install it, so it is available in Git.
I googled your yellow message and found something about TLS 1.2.
Is your windows fully patched? is this windows 10?
[Here ](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/trying-to-install-program-using-powershell-and/4c3ac2b2-ebd4-4b2a-a673-e283827da143)

**Comment by BizWithBruce** [comment]
I did check it now. Twice. I have no idea what they are talking about. Sorry. Thanks anyway

**Comment by BizWithBruce** [comment]
Ok I think the TLS 1.2 thingy did "install I guess
![image](https://user-images.githubusercontent.com/83860716/117549993-ebc54600-b03d-11eb-9318-fba052dcc918.png)

**Comment by BizWithBruce** [comment]
The NuGet is not coming up anymore
So I fixed something which I did not know was a problem. 
But I still cant do what I want to.
YAY

**Comment by BizWithBruce** [comment]
Ok I tried the next thing, changed security protocol again.
And it is still not working
![image](https://user-images.githubusercontent.com/83860716/117550103-a8b7a280-b03e-11eb-9c48-5201bc2d092c.png)

**Comment by BizWithBruce** [comment]
This is what I tried above before restarting powershell
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

**Comment by BizWithBruce** [comment]
So Now I tried all their suggestions

**Comment by BizWithBruce** [comment]
I have no idea if untrusted means anything
![image](https://user-images.githubusercontent.com/83860716/117550768-511b3600-b042-11eb-92ce-8edc6e829ccd.png)

**Comment by BizWithBruce** [comment]
I followed some online suggestions, now looks more broken
![image](https://user-images.githubusercontent.com/83860716/117551252-372f2280-b045-11eb-802f-a1722f662028.png)

**Comment by BizWithBruce** [comment]
Now I am going to stop tinkering further before I break it , if I have not done so already
![image](https://user-images.githubusercontent.com/83860716/117551734-df45eb00-b047-11eb-81c5-f482170831a3.png)

**Comment by rcamarda390** [comment]
well, it says the Gallery is currently unavailable. 
Only thing I had to do was allow powershell to install stuff untrusted, and I had do to that as administrator.
Googling the current error "windows 10 powershell gallery is currently unavailable" I found this: 
https://stackoverflow.com/questions/64011123/powershell-error-saying-the-gallery-is-unavailable-try-again-later

**Comment by rcamarda390** [comment]
did you try this from MrPigs video and below?
https://www.youtube.com/watch?v=Nc-5I-i1EE4


To Install this module first install GIT - https://git-scm.com/download/win​
Then Install PSChia Module with the command below
Install-Module -Repository PSGallery -Name PSChia
If that command fails, make sure you are using admin or if you do not want to use admin run the command below
Install-Module -Repository PSGallery -Name PSChia -Scope CurrentUser
If that command also fails you might need to trust PSGallery with the command below
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted


> Now I am going to stop tinkering further before I break it , if I have not done so already
> ![image](https://user-images.githubusercontent.com/83860716/117551734-df45eb00-b047-11eb-81c5-f482170831a3.png)

**Comment by MrPig91** [comment]
I unfortunately have never seen this error before, thank you @rcamarda390 for helping with this issue. 

@BizWithBruce  I did find a possible solutions from this thread - https://docs.microsoft.com/en-us/answers/questions/257840/powershell-unable-to-find-module-providers-powersh.html
"

I may have resolved this exact same issue today. I noticed that this problem occurred only for my main user on my machine - other user accounts didn't have a problem. I noticed that in my Documents\WindowsPowerShell folder I had a "Modules" folder, which included a module for "PackageManagement." Deleting the entire Modules folder resolved the issue for me.

What's worse, I have OneDrive known folder redirection turned on, which meant this folder was being replicated to every machine where I logged in, which broke PowerShell for me on every machine I touched."

Let me know if this helps please.

**Comment by MrPig91** [comment]
Closing, please re-open if the above suggestion didn't work. Thank you.
