### ISSUE TITLE
Idea: Chia Plot Planner function

### ISSUE THREAD

**Issue by kszabok** [MrPig91/PSChiaPlotter#118]
Is it possible to expand the script function with a "Chia plot planner" to avoid wasting space? So I choose a disk, and the plotter apply the best k32, k33, k34 compilation based on free space.

**Comment by phpfrog** [comment]
There's already a line command you can use called "Get-ChiaKPlotCombination"
Example:
`Get-ChiaKPlotCombination` **|** _Show combinations from all drives_
`Get-ChiaKPlotCombination -DriveLetter d` **|** _Show combinations from just drive **d**_

**Comment by kszabok** [comment]
Thanks 👍

**Comment by MrPig91** [comment]
It would be nice for the GUI to do this automatically, but unfortunately that bring in too much complexity for the current moment. As phpfrog mentioned there are a powershell command to find the best optimizations of space, and from there you will have to setup how you want to plot those combinations. Thank you for the idea :)
