### ISSUE TITLE
Version for Ubuntu.

### ISSUE THREAD

**Issue by InvaderDolan** [MrPig91/PSChiaPlotter#12]
Please, distribute the version for Ubuntu.
Me and other Ubuntu Chia farmers will appreciate you!
Thanks!

**Comment by kreaninw** [comment]
Farmers on Raspberry Pi would love this idea.

**Comment by MrPig91** [comment]
You should be install the module on Ubuntu if you install Powershell 7. Some functions will work with powershell 7 on Ubuntu while others will not. I will be visiting past functions to add compatibility as time permits.
