### ISSUE TITLE
[question] About times in parallel plotting

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#125]
Hello,

Is it normal for the plotting time (per plot) to be almost double when parallel plotting versus solo plotting?

When parallel plotting I made sure that there are enough threads  and enough nvme space ( 3 plots per 1TB ssd) and also enough RAM.
Even more, I have different ssd (SATA SSD) for Temp2.

While I get 5 hours for 1 plot on solo plotting, I get almost 8 hours per plot when plotting 6 in parallel (  with a 8 core i9 and 64 RAM) 

So, is it normal for the plotting time to increase that much per plot in parallel plotting?

P.S. I even TRIM the SSDs hourly.

**Comment by Jacek-ghub** [comment]
Those times are normal.  

When you run just one plot, basically just one physical core is active, so the CPU temps are low, and it can boost frequencies a bit for short times.  The more jobs you add, the more cores are being used, and the frequencies are scaled down to keep the temps low.

You should be fine running 4 plots per 1TB NVMe.  Although, it will slow your times a little bit (not much, though).  Especially, as you have 8 cores, that makes a good split.

**Comment by ClementN** [comment]
Thank you, for the information, @Jacek-ghub .

I have another unclear point about the Temp2. 

I did some tests in parallel. One job using Temp2 (a regular SATA SSD) and one job without Temp2. 

It seems like the one with Temp2 is taking longer (especially in Phase 4).

In that case, I am not sure what is the advantage or why should be advisable to use Temp2.

**Comment by Jacek-ghub** [comment]
Sorry, I don't know anything about that Temp2.  Someone else needs t chime in.

Also, I forgot to mention that depending whether you CPU is with "K" or not, it may be thermally locked to TDP 65W, so you would need to look into that.  That also implies, what cooling you have (stock fan is only good for that 64W TDP).

**Comment by ClementN** [comment]
Thank you for your time, @Jacek-ghub 

It seems like the plotting time is longer with SATA SSD for Temp 2 because their write/read speeds are much lower then the nvme.
