### ISSUE TITLE
Refresh Job

### ISSUE THREAD

**Issue by Sky1414** [MrPig91/PSChiaPlotter#126]
WIth new version 1.0.45 : this name off job is not refresh
![image](https://user-images.githubusercontent.com/83701847/123226505-065f5b80-d4d4-11eb-9bd7-d039c6eab06b.png)
---> 
![image](https://user-images.githubusercontent.com/83701847/123226647-23942a00-d4d4-11eb-8b90-d21369ce3469.png)

**Comment by Jacek-ghub** [comment]
Did you click Load?  It is for me,

**Comment by Sky1414** [comment]
It works, weird ...

**Comment by MrPig91** [comment]
That is interesting. I haven't run into this issue before and there wouldn't be anything in the code that would prevent that value from changing. It could have been just WPF weirdness for a bit or the load button was yet to be pressed. Thank you for reporting this though.
