### ISSUE TITLE
Code on front page

### ISSUE THREAD

**Issue by gannon416** [MrPig91/PSChiaPlotter#13]
I'm no coder, but shouldn the "Start-Sleep -Seconds 3600"  be "Start-Sleep -Seconds $delay"?  ;)

param(
[int]$parallel = 3,
[int]$delay = 3600,
[int]$PlotsPerQueue = 1,
[int]$Buffer = 3390,
[int]$Threads = 2,
[Parameter(Mandatory)]
[string]$tempDir,
[Parameter(Mandatory)]
[string]$FinalDir,
[Parameter(Mandatory)]
[string]$LogDir
)

for ($i = 1; $i -le $parallel;$i++){
$date = Get-date -format yyyy-MM-dd-hh-mm-ss
$logpath = Join-Path $LogDir $date
Start-Process -FilePath powershell.exe -ArgumentList "chia.exe plots create -n $plotsperQueue -b $Buffer -r $Threads -t $tempDir -d $FinalDir | Tee-Object -FilePath $($LogPath)_$($i).log"
Start-Sleep -Seconds 3600
}

**Comment by MrPig91** [comment]
You are absolutely right! Thank you so much for pointing this out. I have updated it.
