### ISSUE TITLE
Networking paths (cifs, nfs etc.)

### ISSUE THREAD

**Issue by Tedybb** [MrPig91/PSChiaPlotter#133]
Hey guys, may be I'm doing something wrong, but I cannot put as final destination of the plot a network share. PSChiaPlotter tells.me that network path does not exists. It actually exists and I have access to it via windows explorer...

**Comment by Jacek-ghub** [comment]
Take a look at that thread:
  https://github.com/MrPig91/PSChiaPlotter/issues/102` (Missing RAID arrays)

**Comment by MrPig91** [comment]
I believe you have to use UNC path sometimes, also Jacek-ghub has provide another thread where this is discussed.
