### ISSUE TITLE
[question] About replotting

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#136]
Hello,

What is the purpose of "replotting"? 

I see it as a new set of features...

**Comment by CDprotector** [comment]
i am interested too. is it preparation for official pools replot ?

**Comment by MrPig91** [comment]
It is in preparation for having to replot for official pools portable plots as CDprotector mentioned. It will basically delete a plot at the end of phase 3 / beginning of phase 4.

**Comment by ClementN** [comment]
Is there a place where I can learn more about the replotting (didn't find it by myself) ?

I understand why but I am missing the how.

It will use an og plot and will transform it somehow into a portable one so the entire plotting process will be shorter for a replot then it should be for a new plot?

**Comment by MrPig91** [comment]
It will not be able to transform the OG plot, it will just delete the OG plots one by one as your create the new portable plot. I am not 100% sure how these portable plots are created at the moment, but I think you will need to use the Pool Contract parameter which you will get from an official pool. I have added that Pool Contract field in preparation for the portable plots as well.

**Comment by ClementN** [comment]
It is clear now. Thank you.

So the advantage of "replotting" is that it keeps the og plot "alive" for farming while the new portable plot is prepared and it will delete the og in the last moment to make room for the new one.

Nice.

**Comment by MrPig91** [comment]
Exactly! It is definitely a feature that will probably only be used during this transition process but I know it is one that people would want and had a couple request for it. Thank you for the question as I am sure some other people are bit confused by it as well. I will be releasing a video sometime this week going over some of the new features.
