### ISSUE TITLE
[question] Option to leave the chia plotting processes running

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#139]
Hello,

If the chia plotting processes are left running when PSChiaPlotter is closed, is it possible to see them again in PSChiaPlotter when re-open?

**Comment by MrPig91** [comment]
It is not possible to see those processes again once PSChiaPlotter is closed unfortunately. I have thought about adding a feature that tries to detect running chia plot processes but have not had the time to add it quite yet.

**Comment by Jacek-ghub** [comment]
Does it mean that at some point we may have PSCP worker (managing plotters) and PSCP [remote] UI (connecting to all workers) modules?
