### ISSUE TITLE
[Enhancement] Ability to aggregate plot tables from multiple plotters

### ISSUE THREAD

**Issue by rcamarda390** [MrPig91/PSChiaPlotter#14]
I'd like to have all my plots from different plotters in one place, then analyze with your tools.
One thought: create sub folders, with the name indication where it came from,like plot1, plot2...
I copy the plot logs from my plotters and put into said folders
Modify chia plotter to add a column to indicate and sort based on the plotter, say the sub folder name, or other means.
This might be easier than tying to use/convert powershell scripting for linux.
mc2

**Comment by MrPig91** [comment]
All my attention will be focused on PSChiaPlotter GUI and I have not plans to add the feature but I love the idea.
