### ISSUE TITLE
MadMax_Full Support

### ISSUE THREAD

**Issue by Alfridus1** [MrPig91/PSChiaPlotter#143]
Just a question  - will you support in the future all features from Madmax? Like another buckets for p3 ? 
Thank you for information! 
Great work!

**Comment by Sekaiji** [comment]
+1
Very important option. Please add it

Thanks

**Comment by Alfridus1** [comment]
> Just a question - will you support in the future all features from Madmax? Like another buckets for p3 ?
> Thank you for information!
> Great work!

Plus: don't wait till copy but just start over the next one + total plot time without copy time please! Thank you very much!

**Comment by MrPig91** [comment]
I will look into this, I have couple small other changes I want to make that I might lump these in with. I need to update my madmax version first though!

**Comment by Sekaiji** [comment]
Would love "don't wait till copy but just start over the next one + total plot time without copy time"

**Comment by MrPig91** [comment]
Buckets for phase 3 has now been added and patched up. I hope to add some other features of MM in the future however some will need to be recreated given that PSChiaPlotter starts each plot process one at time and some of MM feature only work when you have n > 1.
