### ISSUE TITLE
Issue w/ Final Drive Selection (Drive letter mapped to NAS)

### ISSUE THREAD

**Issue by MEBruck** [MrPig91/PSChiaPlotter#147]
First, I really love the look of this program - great job!  Unfortunately, I can't use it YET, because my final drives are out on a NAS, which are mapped on my main node, where the plotting happens. As you noted, these types of drives may not show up on your "Advanced" drive selector, but when I try to use the "Switch to Basic" option, I get an error when I Start Job, that says the Final Directory Does Not Exist. I did verify that the final directory I entered in the "basic' setting DOES exist. I assume this is just a small programming issue, because you can't detect this drive/path in the "advanced" option. Is there any workaround I can do to get past this?  I realize you might have a lot of time to dedicated to something like this, but I'm hoping you might have a quick-fix.  Thank you very much - in advance!

**Comment by MrPig91** [comment]
I will have to look into this further but that is really strange. The basic plotting feature uses Test-Path to ensure the path exists. Can you try running the command test-path with the path you gave it to see if it returns true outside of PSChiaPlotter?

**Comment by MEBruck** [comment]
Thank you for getting back with me. I know you're busy, so it's appreciated. I can check Test-Path, but I want to let you know that I took the advice of another member and used the full UNC path \\xx.xx.xx.xx\share and it worked perfectly, so I'm up and running. LOVE this program BTW. I've cranked out over a hundred plots in a day and a half and it's SO EASY to use! :) I'll go back and check the Test-Path and let you know.

**Comment by MEBruck** [comment]
Ok, Test-Path fails to see my drive path (I:\Farm) that was already mapped to a NAS device. However, it does see the path if I use the full UNC path without utilizing the previously mapped drive (I:).
![Test-Path](https://user-images.githubusercontent.com/13283878/124775927-a5d51300-df04-11eb-872d-799862d05309.jpg)

**Comment by grobalt** [comment]
push :) same issue for me .. all plots on network drives, replotting them would be nice :)

**Comment by MrPig91** [comment]
@MEBruck Sorry for the late response as I was on vacation. I am very happy to hear you found a workaround using the full UNC path. That is so interesting, I have never seen the mapped drive fail while the UNC path still work.
