### ISSUE TITLE
Job waiting free temp space.

### ISSUE THREAD

**Issue by radcuman69** [MrPig91/PSChiaPlotter#151]
I had an issue today where a K33 plot queue finished one plot then went to a "waiting on temp space" type message.  The only other job was a MadMax plot job queue that I started after the K33 queue.  There was 640GB of space free on the temp drive at the time of the message.  I started the queue again but changed the job to the basic temp/final location setup so it doesn't check anymore.  The total space on the temp drive is 931.39gb so there would be plenty of space for the 2 jobs to run.

**Comment by MrPig91** [comment]
Yeah, the temp space safety feature is a bit over zealous. You can also check the box, ignore max parallel checkbox to turn that feature off as well.
