### ISSUE TITLE
ramdisk not availvable?

### ISSUE THREAD

**Issue by Namsoyo** [MrPig91/PSChiaPlotter#152]
I use a 110TB Ramdisk but it's not listened in PSChiaPlotter.

**Comment by MrPig91** [comment]
Yeah sometimes PSChiaPlotter is not great a picking up all available disk. For now I recommend using the basic plotting feature where you can provide the full path to the disk you want to plot on. Sorry for this, but I hope this work around is suitable for now.

**Comment by MrPig91** [comment]
Please use the Basic Plotting feature for now as I do not plan to fix this in the near future. Sorry for any inconvenience.
