### ISSUE TITLE
Stuck @ copying and stopped chia gui farming

### ISSUE THREAD

**Issue by toaz1z** [MrPig91/PSChiaPlotter#153]
Thank you @MrPig91 , amazing work.

Im working on PSChiaPlotter using madmax for three days without any issues, now im facing an issue, stuck on copying processes and this lead to stop farming @ chia gui also!
I tried to change the settings, using different versions of mm but didn't solve the issue.

Thanks

**Comment by ClementN** [comment]
I can confirm same "stuck @ copying - 0%"  with the chia plotter (not madmax), too. 

After first 10 plots working ok, the next 2 are stuck in the copying stage. 

Looking into the Dst folder, it seems like the files are there with the .tmp extension.

**Comment by toaz1z** [comment]
I tried to reinstall pschiaplotter,update module.. didn't help

**Comment by toaz1z** [comment]
Update:
changing final dir. will solve the issue

**Comment by MrPig91** [comment]
The copy phase does not update and will show 0% until it is finished copying. Glad you were able to solve the issue by changing the final dir though.
