### ISSUE TITLE
NFT plots

### ISSUE THREAD

**Issue by nitdk** [MrPig91/PSChiaPlotter#155]
Is it possible to plot for NFT ( to pools )

**Comment by PhattyOgre** [comment]
That is correct. When you go to start a new job, you'll see under the 'Additional Parameters' section that there's a box for it. Check the box next to 'Pool Contract Address' and then add the proper value.

**Comment by MrPig91** [comment]
Yes it is possible and PhattyOgre correctly explained how to do so. Thank you PhattyOgre.
