### ISSUE TITLE
PSChiaPlotter doesn't see Windows JBOD Volumes ( Formated with REFS )

### ISSUE THREAD

**Issue by lionB777** [MrPig91/PSChiaPlotter#158]
I've got several dynamic drives mounted in a JBOD way with windows server 2019, The manager cannot see any of the volumes made this way. I've got 2 of them with 4X 18TB each. Formated with REFS. Any Idea ? Thanks

**Comment by grobalt** [comment]
use the basic menu and enter the drive letter. just the advanced view is not working with the drop down selection

**Comment by lionB777** [comment]
Thanks, it works that way. but any chance to get the advanced view to work ? or is it a windows limitation ?

**Comment by MrPig91** [comment]
I have decided early on to not support dynamic disks since they have been deprecated since 2004. Storage Pools are their replacement. I am sorry for the inconvenience but I am glad the workaround using the basic plotting feature is working.
