### ISSUE TITLE
Assigning temp 1 & 2 drives for madmax and feature request

### ISSUE THREAD

**Issue by Javvegit** [MrPig91/PSChiaPlotter#159]
Hey man,

Thanks for your hard work, much appreciated. Maybe this isnt a issue and its just me being stupid but I cant get the plotter to let me decide how to allocate my temp drives when using madmax. I have a 240 SSD that can handle being tmp2 drive but the plotter seams to ignore it since its too small for the regular plotter and just uses the other drive as temp 1 & 2.

Also I would kindly like to request a feature to start a parallel run with madmax as soon as the previous run finishes P4 and starts to copy.

**Comment by tivikoff** [comment]
"Feature to start a parallel run with madmax as soon as the previous run finishes P4 and starts to copy."
++ . It would be awesome to be able not to wait extra 10-15m of copying when total plot times are ~30m. Madmax supports this by default. Would be cool if this can be implemented in the PSChiaPlotter.

**Comment by MrPig91** [comment]
I would like to add this, but I do not have plans to add this anytime soon. I really just do not want to over promise any features I can't deliver in a timely fashion.  The next best thing would be to have the final drive as your temp drive so it doesn't copy over and having a custom script that transfers your final plot files to their actual final drives if that makes sense. 

As for the issue you mentioned. How are you adding the 2 temp drives? There should be 2 different combo box to select the 1st temp drive and another for 2nd temp drive.

**Comment by RichG123** [comment]
Just wanted to say many thanks for all your hard work but to emphasise the importance of being able to start the next plot when the previous plot finishes, just cannot afford the 15 min or so copy time that is wasted. For this reason alone will regretfully have to go back to using MM on it's own until this feature can be added.

**Comment by MrPig91** [comment]
@RichG123 This feature has now been added.
