### ISSUE TITLE
issue with settings phase 3/4 buckets on 1.0.51

### ISSUE THREAD

**Issue by henhito** [MrPig91/PSChiaPlotter#160]
the bucket setting does not work, it seems to take the setting from buckets under plotting parameters.

**Comment by HeyManGonzo** [comment]
Yes, I noticed that too.

**Comment by MrPig91** [comment]
This will be fixed in a the next update. It will only use the phase 3/4 buckets parameter if you change it from the default of 128, I did this so previous MM version would still work if that value wasn't changed. Bad design on my part.

**Comment by MrPig91** [comment]
This has now been fixed. You will have to check the checkbox for that field to enable this parameter but it should work as expected once checked.
