### ISSUE TITLE
Final Directory Size Limit

### ISSUE THREAD

**Issue by Crimsonking314** [MrPig91/PSChiaPlotter#161]
The app will not let me exceed the number of plots that will fit on a drive so the plots wait for space on the final drive even though space is free. I use a small SSD for a buffer drive and use robocopy to move to final directories.

**Comment by MrPig91** [comment]
I will be adding a ignore final size limit checkbox to bypass this in the next update. Sorry for the late response I have been on vacation. Using basic plotting feature will also bypass this in the meantime.

**Comment by MrPig91** [comment]
You can now disable PSChiaPlotter from checking free space for final drives by checking the checkbox "Ignore Free Space" which will disabling checking if there is enough free space available before starting the plotting process.
