### ISSUE TITLE
Get-ChiaPlottingStatistic could not be loaded

### ISSUE THREAD

**Issue by ddferrer** [MrPig91/PSChiaPlotter#17]
Hello,

I ran the following command for the first time in powershell admin:

`Install-Module -Repository PSGallery -Name PSChiaPlotter`

Went through a couple of prompts to complete installing the module. When I try to run Get-ChiaPlottingStatistic, I get the following error:

_Get-ChiaPlottingStatistic : The 'Get-ChiaPlottingStatistic' command was found in the module 'PSChiaPlotter', but the
module could not be loaded. For more information, run 'Import-Module PSChiaPlotter'._

Any ideas on how to get this module loaded?

**Comment by ddferrer** [comment]
Figured it out. Had to run the following commands in this order.

```
Set-PSRepository -Name "PSChiaPlotter" -InstallationPolicy Trusted
Install-Module -Repository PSGallery -Name PSChiaPlotter
set-executionpolicy remotesigned
Import-Module PSChiaPlotter
```

**Comment by MrPig91** [comment]
Glad you were able to figure it out. I had to make a video about this since so many people ran into the same issue.
