### ISSUE TITLE
Plot infinite function 

### ISSUE THREAD

**Issue by scubammx** [MrPig91/PSChiaPlotter#170]
hallo, what is the new "plot infinite" function in the gui ? i cannot find any info abou this .

**Comment by Jaga-Telesin** [comment]
Pretty sure it means "keep plotting until you run out of space".  As opposed to "plot 1" or "plot 50" which both stop once they hit their limit.

**Comment by scubammx** [comment]
i think this function was already there with "n-1" in the plotter, so i was hoping for an new infinitely  fast plot option !  :-)
thanks for the reply

**Comment by MrPig91** [comment]
Jago-Telesin explained it well. Many people wanted an option for it to just keep plotting. This could be done before by adding a very high number to the total plots but this just makes it a clearer option. As long as you don't have "Ignore Free Space" Checked the plotter should "stop" when there is no more free space, the queues will just be blocked from starting new plotting processes.
