### ISSUE TITLE
Madmax Copy while Plotting

### ISSUE THREAD

**Issue by scubammx** [MrPig91/PSChiaPlotter#174]
Hallo , madmax by default copy the finished plot while is starting phase1 of the next one , but the PSCHIAPLOTTER using madmax wait the copy to be finished  before starting the next plot .
this is a pity, cause we loose 15 minutes per plot,  is there a way to sort it out ?
thanks a lot!

**Comment by MrPig91** [comment]
This has been requested in many different issues. I will starting working on something similar. Please check out the other issues to find more info. 
https://github.com/MrPig91/PSChiaPlotter/issues/173

**Comment by MrPig91** [comment]
This has now been added.
