### ISSUE TITLE
Unable to Check Plots - v1.0.53

### ISSUE THREAD

**Issue by MarFre22** [MrPig91/PSChiaPlotter#178]
Hi, thank you very much for your good work!

After the latest update (v1.0.53), I can't check or autocheck the plots.
I try to check them manually, but it gives-me this error:
![imagem](https://user-images.githubusercontent.com/51057236/125950159-4177881d-0cbe-4a7f-8e3d-6bc0c6813102.png)

Hope this is an easy fix :)

**Comment by MrPig91** [comment]
This was actually an easy fix. I have updated the code and released a new version. Thank you for reporting this.
