### ISSUE TITLE
Ram Column need one more number (show 5numbers, not 4), this is just apearance problem.

### ISSUE THREAD

**Issue by FMeskas** [MrPig91/PSChiaPlotter#18]
If plot gets more than 10GB ram, ChiaPlottingStatistic cant show 5 numbers and shows only first number, another 4 hides. 

![ramcolumn](https://user-images.githubusercontent.com/84009400/117782971-cc4f3880-b24a-11eb-9de4-e4c29e9ae858.JPG)

**Comment by MrPig91** [comment]
Hey good catch! I will update this tonight!

**Comment by MrPig91** [comment]
I have updated the column width from 4 to 5
