### ISSUE TITLE
Plots counted as "completed" and "failed" in the same time

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#180]
v. 1.0.53

Plot While Copy - checked 
MM plotter

It seems for me that all plotted plots are counted both as "completed" and "failed" .
(confirmed on 3 machines)

Anyone else can confirm this behavior?

**Comment by MrPig91** [comment]
Are there any errors in the PSChiaPlotter logs? When did the plots "Fail" was it during the copy phase?

**Comment by MrPig91** [comment]
So the only way I can see this happening is if the Copy function failed after line 61 and on or before line 72 - https://github.com/MrPig91/PSChiaPlotter/blob/main/PSChiaPlotter/Private/Start-PlotCopyPhase.ps1

**Comment by ClementN** [comment]
Thank you, @MrPig91 

There are no errors in the logs. 

I don't know the exact moment when plots fail. I suppose is during the copy phase. I will keep an eye on them and let you know. 

However, in the Log Stats, the Copy Time is  0. 

Anything else looks normal. The .plot files are on the destination folder as expected.

**Comment by MrPig91** [comment]
Well I am glad to here that it at least completed the process and is just reporting incorrectly. The copy time should show 0 for this since that stat comes from the Log file of MM and PSCP is doing the actual copying. I wonder if I should append the log file so that the stat will show up on that.

**Comment by kien23** [comment]
I have encounter the same issue which COPY REPLOT file failed at destination folder.
Error is not logged.
![image](https://user-images.githubusercontent.com/1800194/126115490-001127b3-c56d-4db7-b494-da3e91edc38b.png)

The plotting is done with MadMax Plotter + Replot.
Because of the fail, file continue to pile up in TMP drive, and job will stop after TMP drive is full.

**Comment by ClementN** [comment]
The problem is solved in 1.0.55 for me.

Probably was linked with the "check plots" bug.

**Comment by MrPig91** [comment]
I am thinking that must be the case as well given when the plot is added to the completed and failed lists. Thank you for the update.
