### ISSUE TITLE
Job fail when copy to final destination (Replot)

### ISSUE THREAD

**Issue by kien23** [MrPig91/PSChiaPlotter#185]
Version 1.0.55

I encounter the below issue when replot is done with madmax, and the file was trying to copy to destination folder but it failed.
No error is recorded in the log.
![image](https://user-images.githubusercontent.com/1800194/126116588-1ab910fe-1e76-40bb-a07f-8f869bb524bd.png)

The consequences is that, the failed copy file continue to sit in TMP drive (plotting drive), piling up and TMP drive will run out of space, then job is stopped.

Is it possible to add "Final Drive" column in All Runs tab, so we can have a better idea whether this happen to single drive or random drive?

or if it possible to return the copy fail error in the log?

**Comment by MrPig91** [comment]
Are you looking at the log file for the plot or the PSCP log file? If it did fail to copy it should have recorded the error that caused it to fail. I will add more info to the all runs tab including the "Final Drive" column you suggested.

**Comment by kien23** [comment]
Please see the plot log below.
![image](https://user-images.githubusercontent.com/1800194/126176146-dba47f9f-a2b6-4e13-ad22-670b5c62c02d.png)

As for PCSP log, not sure there is no log recorded.
![image](https://user-images.githubusercontent.com/1800194/126176725-2b7fb095-adea-4ee5-b5b8-924876793e44.png)

**Comment by MrPig91** [comment]
So strange. I think a lot people don't have the PSCP log file being created. I will have to look into this. In the next update I plan to have the copy process be logged to the plot log file  as well. I think I will have it retry to copy if it fails as well.

**Comment by kien23** [comment]
Thank you!
