### ISSUE TITLE
Cannot add network drives to final drives.

### ISSUE THREAD

**Issue by DroptheHammer** [MrPig91/PSChiaPlotter#192]
With the actual chia GUI, I can add my network NAS drive (which farms for me on it's local node) to the final directory.  For the time being I can copy in bulk manually, but it would be nice if the PSPlotter would recognize network mapped drives or network locations as valid for moving the final plots to (archiving?).

**Comment by chakumon** [comment]
a simple reboot solves this for me..

**Comment by Extra-life** [comment]
Works for me too

**Comment by DroptheHammer** [comment]
> 
> 
> a simple reboot solves this for me..



> 
> 
> Works for me too

I've done multiple reboots.... Tried my laptop and 2 other desktops and VMs.  I cannot get it to recognize remote drives in my list. It continues to only show locally connected drives.   Also, these drives and locations have been operating as windows shares for years on all my other applications from backup, to SQL servers, plex servers, file sharing and game servers.  So I'm just very unsure why PSChia specfically is unable to see them.

**Comment by DroptheHammer** [comment]
![image](https://user-images.githubusercontent.com/79561845/128104061-01a1e774-fb6f-406f-8ea4-184058eef49a.png)

![image](https://user-images.githubusercontent.com/79561845/128104132-0931a103-645a-4b0d-b22d-c2ff1f0adada.png)

I want it to show the H: I: Y: & Z: Drives... But they never show... reboot, refresh.. whatever.

**Comment by DroptheHammer** [comment]
http://woshub.com/how-to-access-mapped-network-drives-from-the-elevated-apps/

With the link above the issue seems to be resolved.  The main problem is all my network connections were mapped as my local user account, not as my local admin account (this is normal for Windows 10, admin accounts don't by default have access to your network drives).   

Since the setup had required administrator powershell to install PSChiaPlotter, I had always been running an elevated prompt to access the tool.  However, when I open powershell as a normal user... PSChiaPlotter can see all my networked drives... 

Hopefully this helps someone else in need.  The answer is to..

1. Install PSChiaPlotter as per the normal wiki
2. Ensure when you RUN PSChiaPlotter with the intent of plotting to a network drive, that you do so with a standard user, or NON-elevated client/powershell.

![image](https://user-images.githubusercontent.com/79561845/128104835-2148e174-82bd-4269-96c0-bed5e92bfd2b.png)

**Comment by DroptheHammer** [comment]
I'm running some plots overnight with targets to network drives and assuming all 12 are written.. I'll close this ticket tomorrow.

**Comment by DroptheHammer** [comment]
Plots successfully written! issue closed!
