### ISSUE TITLE
Can't find chia.exe

### ISSUE THREAD

**Issue by warrengalyen** [MrPig91/PSChiaPlotter#214]
With the release of Chia 1.6.1, the default installation path has changed to "..AppData\Local\Programs\Chia\..." which is preventing me from running a job. I added the new folder path for Chia to the Powershell environment path and removed the old one but your script seems to be ignoring this as I get a prompt saying it can't find Chia in the old "chia-blockchain" path.

There doesn't seem to be any other way to set the default Chia path.

**Comment by Critter-ID** [comment]
I had the same problem. You need to edit

C:\Program Files\WindowsPowerShell\Modules\PSChiaPlotter\1.0.55\PSChiaPlotter.psm1

all

"$ENV:LOCALAPPDATA\chia-blockchain\app-*\resources\app.asar.unpacked\daemon\chia.exe"

to

"$ENV:LOCALAPPDATA\Programs\Chia\resources\app.asar.unpacked\daemon\chia.exe"

**Comment by warrengalyen** [comment]
@Critter-ID Thanks for identifying that line. Not sure why the Setup instructions define a global variable for the chia.exe path when this is completely ignored and hard-coded.  I noticed the path is referenced across about a dozen files as well in the module path, so these need to replaced too to get it working correctly.

I will probably do a fork of this repo with changes to get it working again for other users since it hasn't been updated in a long time.

**Comment by MrPig91** [comment]
I went ahead and updated the module. It should work with the new version now.

**Comment by Critter-ID** [comment]
@MrPig91 glad to see you in this thread, thanks for this module again

**Comment by Critter-ID** [comment]
@warrengalyen so that is the way we closed our little question :)

**Comment by warrengalyen** [comment]
@MrPig91 Thanks for jumping on that! Wasn't expecting such a quick response.

**Comment by warrengalyen** [comment]
@MrPig91 Tossed some ETH your way since I find this tool very useful.

**Comment by MrPig91** [comment]
@warrengalyen thank you so much, I really appreciate it! I am also happy to hear you find the tool useful.
