### ISSUE TITLE
Add-Content: Could not find a part of the path because it's looking for a OneDrive Documents folder

### ISSUE THREAD

**Issue by DontWorryScro** [MrPig91/PSChiaPlotter#23]
I know this is not an issue with your script.  I just don't know how to go about making powershell use my regular documents folder path over some OneDrive\Documents\windowsPowershell path

**Comment by MrPig91** [comment]
If you are using OneDrive I would have it just use that path and then add the "WindowsPowerShell" folder to that Documents folder to have it work.
