### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Gohsteu** [MrPig91/PSChiaPlotter#24]
Hello MrPig,

Thanks for the Videos on YouTube, really help me out!
Also i could see that PowerShell is similar to my Ubuntu lesions back to school..

My Doubt is:

Is there any association with my Wallet/keys of my Farming machine if i install you Module?
Or lets say it frankly could there be a backdoor to look in to my Chia Wallet/Plots?

Thanks!

**Comment by MrPig91** [comment]
If you are using online code, there is always risk since the person writing the code could add something that makes that code malicious. However, you can read all the code here, so you can feel confident in what you are running on your computer.
