### ISSUE TITLE
Get-ChiaPlottingStatistic:  size of the columns Temp and Final

### ISSUE THREAD

**Issue by pipone** [MrPig91/PSChiaPlotter#25]
I wonder if there is a way to parametrize the size of the columns **Temp** and **Final**
I am parsing Linux log files and I had to override ChiaPlottingStatistic.ps1xml to get wider columns. 

i.e.

Temp
-----

/mnt/...

vs

Temp
-----

/mnt/hddblack2

Wide setting of 5 caracters only works for Windows Driver letters and not for Linux.

Thank you, great work.

**Comment by MrPig91** [comment]
I could make another view for Linux that could access through the format-table -View  command

**Comment by MrPig91** [comment]
I no longer have time to add this in, I am sorry.
