### ISSUE TITLE
DONE -  PLEASE MERGE IT : Code for add $WindowName To Window Tittle  (Custom SSD Plotter Names in WindowTitle)

### ISSUE THREAD

**Issue by goyetus** [MrPig91/PSChiaPlotter#27]
Adding custom $WindowName Parameter to your Script   (For multiple Plotting in different SSD) 
Example:   Plot 1 :  SSD Sabrent.    Plot 2:  SSD 960 Evo ....

Code Uploaded to:
https://github.com/MrPig91/PSChiaPlotter/pull/30/commits/f4f360b84050ec3c7fd0c817d2146a32d10de06a

Pull Request:
#30 

Code below :

**Comment by goyetus** [comment]
Edit:  DONE  .  Added $WindowName  as String Variable. 
---------------------------------------------------------
PLease,  Add this to your code :)
--------------------------------------------------------


function Start-ChiaParallelPlotting {
 [String]$WindowName,		
 [Parameter(Mandatory)]
}

-----------------------------------------------

$processParam = @{
            FilePath = "powershell.exe"
            ArgumentList = "$NoExitFlag -Command Start-ChiaPlotting -TotalPlots $plotsperQueue -Buffer $Buffer -Threads $Threads -TempDirectoryPath $TempDirectoryPath -FinalDirectoryPath $FinalDirectoryPath -LogDirectoryPath $LogDirectoryPath -WindowName $WindowName -QueueName Run_$Queue"
        }

---------------------------------------------

$host.ui.RawUI.WindowTitle = "$WindowName | $QueueName - Plot $plotNumber de $TotalPlots | Chia proceso Id - $($chiaProcess.id)"

**Comment by goyetus** [comment]
https://i.imgur.com/StvtyQc.png

**Comment by goyetus** [comment]
https://github.com/MrPig91/PSChiaPlotter/pull/30/commits/f4f360b84050ec3c7fd0c817d2146a32d10de06a

**Comment by MrPig91** [comment]
Nice, I would like it to not be mandatory since not everyone will want to change it. Possibly add a default value and take away the mandatory parameter attribute and I will merge it.

**Comment by goyetus** [comment]
Please,  Modify it as you want 🙂

Dont need to merge my script,  is an easy task,   more for you!!!   (Im a noob in PS coding)

Regards !!!
________________________________
De: Syrius Cleveland ***@***.***>
Enviado: lunes, 17 de mayo de 2021 15:19
Para: MrPig91/PSChiaPlotter ***@***.***>
Cc: goyetus ***@***.***>; Author ***@***.***>
Asunto: Re: [MrPig91/PSChiaPlotter] DONE - PLEASE MERGE IT : Code for add $WindowName To Window Tittle (Custom SSD Plotter Names in WindowTitle) (#27)


Nice, I would like it to not be mandatory since not everyone will want to change it. Possibly add a default value and take away the mandatory parameter attribute and I will merge it.

**Comment by MrPig91** [comment]
I have added this with the latest merge on my branch. Thank you for the suggestion and the suggested code.

**Comment by goyetus** [comment]
Version 1.1.5 Updated and working perfect :)

THANKS !!!! :)
