### ISSUE TITLE
Suggestion: Delete Temp files when Stop-Process ID

### ISSUE THREAD

**Issue by goyetus** [MrPig91/PSChiaPlotter#28]
Stop-Process  is wonderfull ,  but  it leaves a lot of files in the TEMP drive ,  that can cause fails with the next plots  cause to decreased space.  

Any way to delete files when you kill a process?     (I know it´s not an easy task) 

Regards!!!

**Comment by MrPig91** [comment]
Yes! I the temp files have the plot id in the file names so you can have it automatically delete those files if the process has an exit code other than 0.

**Comment by goyetus** [comment]
Cant find the Plot Id in the code......  
Will search better :)

Regards

**Comment by MrPig91** [comment]
Hello! I had added this to my code and so cancelled chia plotting processes should automatically delete the temp files. I made a YouTube video explaining how this is done in cases you want to experiment with it in your own scripts. https://www.youtube.com/watch?v=FF_AgB04Ccg
