### ISSUE TITLE
Show "Time_started" in Outpup of ChiaPlottingStatistic

### ISSUE THREAD

**Issue by mimeie** [MrPig91/PSChiaPlotter#33]
Hi

Is there a way to show the "time_started" attribute in the output result?

Thanks
Michael

**Comment by MrPig91** [comment]
You will have to create your own view to have that show. You can do this by running the following command 

Get-ChiaPlottingStatistic | Format-Table -Property *

This might output more than your powershell window can show, you can specify which properties you want to show as well.

Get-ChiaPlottingStatistic | Format-Table -Property Time_Started, KSize

Adding each property you want separated by comma.
