### ISSUE TITLE
a Wish

### ISSUE THREAD

**Issue by Lc001tr** [MrPig91/PSChiaPlotter#37]
Ty for great script.
Can you just shorten the "hrs" to "H" and shorten 2 point values to 1 value after the "." then add a column to see start time ? )within the chiaplottingstatistics)

it would be really good to see start time in that table.

**Comment by Lc001tr** [comment]
shortening k-size and threads maybe :)

**Comment by Lc001tr** [comment]
About Plotview Table :
I believe a date like DD/HH:mm should be good. 
And an ID with 2 coloumns. (maybe starting 4 digits of file name like 1-9cca)
About start plotting 
we need time elapsed too. it would be good to see. I know there is starting time top but anyways.

**Comment by jduraes** [comment]
> Ty for great script.
> Can you just shorten the "hrs" to "H" and shorten 2 point values to 1 value after the "." then add a column to see start time ? )within the chiaplottingstatistics)
> 
> it would be really good to see start time in that table.

To be honest, I would much prefer something in the lines of "hh:mm" (5 digits) instead of (for example) "6.17 hrs" (8 digits) or "39.68 mins" (9 digits). Especially because the decimal points forces you to always have to calculate how much that would be in "real" minutes or seconds by converting a fraction of the time.

**Comment by MrPig91** [comment]
Thank you for your input and feedback. For you requests.

1. I can see the benefit of having that view but I have about 5 different request for different default views, so I don't think I can make a default view that will suit everyone. I will also be focusing on the GUI and think the default view is sufficient enough and can easily be modified in its .ps1xml related file. There is an ID property now, but not in the default view.
2. I will look into adding this. I like it. 
3. Final Directory bug you mention has now been fixed. Thank you for pointing this out.
