### ISSUE TITLE
multible drives support

### ISSUE THREAD

**Issue by AmirRezaei** [MrPig91/PSChiaPlotter#40]
Could you add support for running parallel plotting on multiple drives?

**Comment by Falacio** [comment]
You can open a new powershell window and start another queue for any disk

**Comment by AmirRezaei** [comment]
Yes, I thought if I could send an array of drives as parameter.

**Comment by MrPig91** [comment]
I am currently working on PSChiaPlotter GUI and all my focus will be on that, which will support this feature.
