### ISSUE TITLE
Incorrect display in PowerShell 7.0

### ISSUE THREAD

**Issue by ChemForce** [MrPig91/PSChiaPlotter#44]
I'm running
Start-ChiaHarvesterWatcher
and get some incorrect picture
![Pic1](https://user-images.githubusercontent.com/39826432/120038995-c9a36000-c00c-11eb-8a97-234611f14f96.JPG)
but header info is ok...

And some trouble after running
Get-ChiaHarvesterActivity -Summary
![Pic2](https://user-images.githubusercontent.com/39826432/120039030-db850300-c00c-11eb-9638-cd4861874ae0.JPG)
Runtime is absent and ChallengesPerMinute incorrect

Any clues why?

**Comment by MrPig91** [comment]
Unfortunately, I am unable to fix the display since some consoles just don't support VT100. Are you using the native pwsh window or is it embedded in another program (like putty) I don't recognize the icon in the top right. I did fix the negative number in that latest release of the module.

**Comment by ChemForce** [comment]
In that case I'm using Native PowerShell 7.0 on Win 7.

On other rigs i have Powershell 6.0 on Win10 and it works just fine...
