### ISSUE TITLE
Start-ChiaHarvesterWatcher (Attempted to divide by zero)

### ISSUE THREAD

**Issue by JobbeDK** [MrPig91/PSChiaPlotter#46]
Hello

Im getting this error for each logfile when trying to run Start-ChiaHarvesterWatcher

```
RuntimeException: C:\Users\jsk\Documents\PowerShell\Modules\PSChiaPlotter\1.0.18\PSChiaPlotter.psm1:491
Line | 
491  |              $harvesterActivity = [pscustomobject]@{
        |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        | Attempted to divide by zero.
```

**Comment by MrPig91** [comment]
So the only time that the function really has a chance to divide by zero is when calculating the FilterRatio which divides the eligible plots by total plots. I have seen total plots show up as zero if the harvester is not setup correctly (not adding any paths to plots), could this be possible in your case?

This is the line that could be causing the issue if you total plots is equal to zero "FilterRatio = $Matches[2] / $Matches[6]"

**Comment by JobbeDK** [comment]
Hmm, good question. Everything seems to be working, I regularly see plots passing the filter, and i see about 6 tries pr minutes.
This is from my log:
`
2021-05-30T15:44:51.903 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 79052fbebf... Found 0 proofs. Time: 0.33700 s. Total 149 plots
2021-05-30T15:45:00.295 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 79052fbebf... Found 0 proofs. Time: 0.39802 s. Total 149 plots
2021-05-30T15:45:11.038 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 79052fbebf... Found 0 proofs. Time: 0.32812 s. Total 149 plots
`
All my plots are on a network share though. From chia.exe plots show: \\172.50.50.45\plots\
Can that be the issue?

**Comment by phpfrog** [comment]
I'm running across this too, but with less plots (currently 32). The plots are on a shared drive as well.

**Comment by Mar-85** [comment]
![image](https://user-images.githubusercontent.com/25620696/120869673-e0a6fc80-c58e-11eb-96e1-2c6375deeb59.png)
Running acros this as well with the ChiaHarvesterActivity, when i use the watcher its the same. Works on my full node computer, trying to use it on my harvester and not working.

**Comment by MrPig91** [comment]
@phpfrog has added a try and catch block for this property to prevent it the error. I have merged his pull request so this should be fixed in the latest release.
