### ISSUE TITLE
Suggestion: A Blue or Golden Colour for ProofsFound ?

### ISSUE THREAD

**Issue by StHaneCrypto** [MrPig91/PSChiaPlotter#48]
Hi, thanks for your great job, is it possible to add a little function in the Start-ChiaHarvesterWatcher, that change the proofs found's colour ? Something like that : 

if ($harvesterActivity.ProofsFound > 0){
                    $RGB = ....
                }

Thanks

**Comment by MrPig91** [comment]
Most definitely, I will add this in the next couple of days. Thank you for the suggestion :)

**Comment by StHaneCrypto** [comment]
If it can help you here is what I modified on my machine to have other colors less aggressive and a little fun with sound

`
$proofsFound += $harvesterActivity.ProofsFound
                $TotalLookupTime += $harvesterActivity.LookUpTime
                $AverageSpeed = [math]::Round(($TotalLookupTime / $TotalAttempts),5)
                $TotalFilterRatio += $harvesterActivity.FilterRatio
                $newRatio = [math]::Round(($TotalFilterRatio / $TotalAttempts),5)
                $eligibleplots = " "

                $RGB = [math]::Round(((255 * $harvesterActivity.LookUpTime * $Sensitivity) / 5) * 1.25)
                
                # If it's too long ---> color in in red
                if ($RGB -gt 255){
                $red = [math]::Min($RGB,255)
                $green = 52
                $blue = 52

                $a = new-object –type system.media.soundplayer
                $a.soundlocation = "C:\Users\Metallophone.wav" 
                $a.play()

                Add-Type -AssemblyName System.speech
                $speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
                $speak.Speak("It's too long to answer Bro !")
                
                }
                # if time's okay ---> color in grey
                if ($RGB -lt 255){
                $red = [math]::Min(($RGB+30),255)
                $green = [math]::Min(($RGB+30),255)
                $blue = [math]::Min(($RGB+25),255)
                }
                # If Proof Founded ---> color in beautiful green
                if ($harvesterActivity.ProofsFound -gt 0){
                $blue = 0
                $green = 153
                $red = 51
                
                $a = new-object –type system.media.soundplayer
                $a.soundlocation = "C:\Users\Applaudissements.wav" 
                $a.play()

                Add-Type -AssemblyName System.speech
                $speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
                $speak.Speak("You got it Bro!")

                }

                if ($harvesterActivity.EligiblePlots -gt 0){
                    $eligibleplots = $harvesterActivity.EligiblePlots
                }         
                $host.UI.RawUI.WindowTitle = "Total Attempts: $TotalAttempts  ||  LookUp Time - Best: $BestSpeed, Worst: $WorstSpeed, Avg: $AverageSpeed || Over 1 Sec:$Over1Seconds, Over 5 Sec: $Over5Seconds, Over 30 Sec: $Over30Seconds  ||  FilterRatio: $newRatio  ||  Proofs Found: $proofsFound || RGB: $RGB"
                Write-RGBText -Text "$eligibleplots|" -bRed ($red) -bGreen ($green) -bBlue ($blue) -NoNewLine -UnderLine

`

**Comment by MrPig91** [comment]
Thank you so much for the sample code, it made it super easy for me to add the darkmode feature out. I didn't add the sounds just to keep it simple and to have less things that could possibly break, I like that you added it to your though. I also added the color block for found proofs to be blue.
