### ISSUE TITLE
Add Custom Job ID

### ISSUE THREAD

**Issue by RealMuhko** [MrPig91/PSChiaPlotter#54]
Hello,

Thank you for a super nice and user friendly GUI.

I would like to suggest a new and simple feature for future revisions of the PSChiaPlotter...

It would be great if an option of inputting a Custom Job ID # when creating a new job could be added.

So fx. when I create a new job, an input textbox could be added to ask for the Job ID # - If the textbox is left blank, then job ID # could be the default value.

Thanks in advance and thank you again for this great piece of software.

Brgds,

Martin.

**Comment by MrPig91** [comment]
Maybe something like a Job name field? I do feel like the the job # makes it a little hard to see what is what at glance.

**Comment by Jaga-Telesin** [comment]
Job name field would be great!

**Comment by RealMuhko** [comment]
Yes, A job name field would be excellent. In that field any own/custom reference could be added when creating the job.

**Comment by MrPig91** [comment]
The Job Name has been added. Let me know if this suits you needs. Might remove the Job Number from the datagrids or maybe have it as tool tip when hovering over the Job Name cell. Thank you for this feedback. Please open up a new issue if new problems arise from this release. I really changed more than I should in one release but there was a lot of feedback that I wanted to address.
