### ISSUE TITLE
Temp Drive (two 2TB NVME running in Raid 0) is not showing up in the Directories section

### ISSUE THREAD

**Issue by PlotNoob** [MrPig91/PSChiaPlotter#55]
Hello, I have 3 NVME SSDs for plotting. Two of them are running in RAID mode, so I have two temp directories. Only one of of the drives is showing up in the GUI (the non-RAID drive). The RAID directory is missing entirely. I attempted to just manually type in the directory but it did not work.

The Temp Drive exists:![Temp Drive](https://user-images.githubusercontent.com/85456572/120937006-9a59b680-c6d0-11eb-89a3-8b9ec0708e62.png)

It is not listed in the directories in the GUI:![List of Directories](https://user-images.githubusercontent.com/85456572/120937037-b65d5800-c6d0-11eb-843b-3fae8d716cf8.png)

When I add a random directory and attempt to manually enter the directory I want, the drive letter in the box on the left refers to the randomly added directory, not the manually typed one:![Drive Letter](https://user-images.githubusercontent.com/85456572/120937022-a776a580-c6d0-11eb-92c0-5636fbfab7d5.png)

In any event, any ideas on how to get the drive to show in the directories?

**Comment by FrankieCheese** [comment]
I'm running Windows Server 2019 and it looks like and RAID drives are not accessible for plotting, or to place a completed plot if you're using a second machine to create plots.  Chia itself (run via command line) doesn't like remote server drive mappings, but it can use the UNC paths.

**Comment by PlotNoob** [comment]
Thanks for the quick response. It sounds like the "workaround" for me will be to reformat the NVMEs as basic volumes. It will sacrifice 1 plot from total parallel plotting capacity but the trade off is worth it because your tool will make the plotting process for efficient since I always end up losing a few hours of plotting overnight. Invariably, by the time I wake up most of the plots have finished. It's not a terrible problem to have since I'm able to plot around 70 plots a day. It's actually pretty baffling that the Chia GUI doesn't have the option to queue up parallel plots. 

In any event, I very much look forward to your next iteration. Based on your video, it seems that there is demand for queuing up new plots to start when phase 1 is complete on previous plots. I second that motion!

Thanks again for all your hard work. Your contributions are a boon to the community.

**Comment by sk00t3r** [comment]
Are you using a hardware raid or software raid? I only am using the PSChiaPlotter on one of my servers for testing but I have a lot of hardware and can test different configurations. I can not replicate the issue others are having with raid or mapped drives. As a quick test I made a raid 0 with 8 146gb 15k sas drives and ran the Plotting utility. More information on your setup would allow me to be able to test different configurations and possible help. With that said you might be able to leave your raid just as it is and create a mount point or symbolic link to a folder on a drive that the Plotter sees. For instructions check out my 2nd post in this thread: 
[Issue #51](https://github.com/MrPig91/PSChiaPlotter/issues/51)

Here is the screen grab of the Plotter picking up my raid.
![server 2019 raid temp drive](https://user-images.githubusercontent.com/15352487/120984045-42f72d00-c748-11eb-8bf9-5a869ea03fb7.PNG)

**Comment by F47991** [comment]
I am having the same issue. I have 6 SSD's in a Software RAID 0 created in Windows Disk Manger (Dynamic Disks).

The reason that they are not showing up in the GUI is because the Powershell function `Get-Partition` and `Get-Disk` used in the Private Function `Get-ChiaVolume` does not return Dynamic Volumes.
The Variable `$AllVolumes` in the Function `Get-ChiaVolume` includes the disk, but as the rest of the PS functions don't understand Dynamic Disks they are filtered out.

Would it be possible to type the path manually?

**Comment by sk00t3r** [comment]
Have you tried changing the mount path? Point it to an empty folder on a drive that does show up.

**Comment by PlotNoob** [comment]
Hello Sk00t3r, thanks for the tip. So far, I've created a symbolic link on a drive that is visible, but that doesn't seem to work. I don't know how to create a virtual mount, but that seems to be a viable option. I'll let you know when I figure it out and whether it worked.

**Comment by MrPig91** [comment]
I will try to rewrite Get-ChiaVolume function so that it can see Dynamic Volumes. I also need to add drives that do not have a drive letter assigned to them. I first filtered those out as an easy way to filter out recovery drives and/or reserved drives that wouldn't be used. Thank you for all the detailed information.

**Comment by sk00t3r** [comment]
@PlotNoob Try this - 
Create an empty folder on a drive that currently has a drive letter and can be seen by the plotter. Open File Explorer, right click "This PC" then click "Manage". Navigate to "Disk Management" on the left then find your drive and right click on it. Select "Change Drive Letter and Paths..." then click "Add..." then select the radius button that says "Mount in the following empty NTFS folder:" Browse to the folder you created and that should set the mount point. Inside the Plotter make sure you use the path to the folder you created and it will write all the data to the drive that you do not have a letter for.

**Comment by FrankieCheese** [comment]
> Are you using a hardware raid or software raid? I only am using the PSChiaPlotter on one of my servers for testing but I have a lot of hardware and can test different configurations. I can not replicate the issue others are having with raid or mapped drives. As a quick test I made a raid 0 with 8 146gb 15k sas drives and ran the Plotting utility. More information on your setup would allow me to be able to test different configurations and possibly help. With that said you might be able to leave your raid just as it is and create a mount point or symbolic link to a folder on a drive that the Plotter sees. For instructions check out my 2nd post in this thread:

I'm running software raid (W2K19 server standard), the drives are setup as windows storage.  10 SAS drives and 9 SATA drives, Two pools (SAS and SATA). Created 2 shares from the pools.

I didn't think of creating symbolic links.  here's a screen shot of what I've got.  Let me know if you need to see some other bit of information.

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/85470992/121034840-94b0af00-c76a-11eb-983d-36ce26668d48.png">
inks.

**Comment by PlotNoob** [comment]
@sk00t3r 
Thanks for that. I followed your instructions but the path doesn't end up showing in Chia Plotter.  I opened a second instance to see if that helped, no luck. I tried selecting the parent directory along with the mounted folder path, and that doesn't work. The drive where the mount is located is telling the Chia Plotter the size of the drive, which is much smaller than the size of the NVME, and that's causing the Plotter not to run while it waits for space.

**Comment by sk00t3r** [comment]
@PlotNoob and @FrankieCheese I have some free time right now so I will set up a rig that copies yours and others that are having a similar issue. Would be nice if there was a Discord server that we could use for all things related. ;)

**Comment by F47991** [comment]
It seems to work with the mounted drive.
Mount the Software Raid volume to a folder on the C: drive and then add the C: drive in Chia Plotter and point it to the folder where you mounted the disk.

I mounted my Chia Temp volume as C:\ChiaTemp and in the Plotter add C: drive an specify path C:\ChiaTemp\Chia.

**Comment by PlotNoob** [comment]
@F47991 that's exactly what I did but the Plotter doesn't acknowledge the size of the target, Chia Temp, it looks at the size of the drive, C:, so it doesn't let me start the plots in the plotter because it thinks there is not enough room.

**Comment by F47991** [comment]
@PlotNoob ran into the same issue when it tried to start the second job.

**Comment by sk00t3r** [comment]
I was finally able to replicate the issue when using storage pools or dynamic disks, and where your plotting (temp) drive is larger than your storage (final) drive. This however is not an ideal setup. Also I should add that whenever possible you really want to use a raid card. IMHO I would set them up as individual drives if I could not do a hardware raid.

**Comment by sk00t3r** [comment]
I was able to get volumes created using storage pools to work. I just removed the references to Get-PhysicalDisk. It works but its not clean, and it breaks fetching the media type.

```
function Get-ChiaVolume {
    [CmdletBinding()]
    param()

    #grabbing all volumes, partitions, disks, and physicaldisks at once since it has proven to be faster
    $AllVolumes = Get-CimInstance -Namespace "ROOT/Microsoft/Windows/Storage" -ClassName MSFT_Volume |
        Where {$_.DriveLetter -ne $Null} | sort -Property DriveLetter
    $AllPartitions = Get-Partition
    $AllDisks = Get-Disk
    
    foreach ($volume in $AllVolumes){
        try{
            $partition = $AllPartitions | where DriveLetter -eq $volume.DriveLetter
            $disk = $AllDisks | where DiskNumber -eq $partition.DiskNumber

            $Label = $volume.FileSystemLabel
            if ([string]::IsNullOrEmpty($volume.FileSystemLabel)){
                $Label = "N/A"
            }
            if ($disk){
                $ChiaVolume = [PSChiaPlotter.ChiaVolume]::new($volume.DriveLetter,$Label,$volume.Size,$volume.SizeRemaining)
                $ChiaVolume.BusType = $disk.BusType
                $ChiaVolume.MediaType = $disk.ProvisioningType
                $MaxTempCount = [math]::Floor([decimal]($volume.size / (239 * 1gb)))
                $ChiaVolume.MaxConCurrentTempChiaRuns = $MaxTempCount
                $ChiaVolume
                Clear-Variable Disk,Partition,MaxTempCount
            }
        }
        catch{
            Write-PSChiaPlotterLog -LogType "Error" -LineNumber $_.InvocationInfo.ScriptLineNumber -Message $_.Exception.Message -DebugLogPath $DataHash.LogPath
            Write-Warning "Unable to create a ChiaVolume from driveletter $($volume.DriveLetter)"
        }
    }
```

**Comment by MrPig91** [comment]
So the storage pools show up if you leave out the Physical disk part? Maybe we can put that in a if statement to grab the MediaType and then if it is not found then have it set MediaType to unknown. There is also the command Get-StoragePool, that might be useful.

**Comment by MrPig91** [comment]
I have revamped the Get-ChiaVolume function and updated the ChiaVolume class. Volumes are now tracked by their UniqueId instead of drive letter (should have been this way to start with). The changes should also allow volumes without drive letters to be used now and if what sk00t3r said above is true about RAIDs being seen when physcialdisk was removed, then this updated code should find those now too. I don't have any RAIDs or storage pools on my computer so I can't test that out. Currently the updated code is still on another branch called GUIUpdate and I have not merged yet.

**Comment by MrPig91** [comment]
I have released a new version, let me know if the RAID is now able to be seen. Also I do not plan to add dynamic disks to the PSChiaPlotter after reading up on them. Everywhere I read said not use them since they have been deprecated for almost 2 decades now and to use Storage Pools instead. Please open up a new issue if new problems arise from this release. I really changed more than I should in one release but there was a lot of feedback that I wanted to address.

**Comment by sk00t3r** [comment]
100% agree on not using dynamic disks. Storage Pools are a much better solution. With that said I have tested each scenario and can verify that raided disks now work when using storage pools. However unless I am doing something wrong (a very real possibility) I can not get Dynamic Disks or disks with no drive letter working. OS used is Windows Server 2019 Standard. Sorry for late testing, free time is hard to come by as we all know. I can spin up another server and install Windows 10 on it if needed. Here are the results:
C: local SSD OS drive - showing
D: raid 0 dynamic - not showing
E: dynamic no raid - not showing
F: storage pool simple (raid 0) - showing  
G: storage pool mirror (raid1) - showing 
Z: mapped network drive - showing
![test results](https://user-images.githubusercontent.com/15352487/121218091-70c79900-c850-11eb-8d9b-ec651e31c8f7.PNG)

**Comment by sk00t3r** [comment]
Ignore my last comments about drives without a drive letter not showing on the main plotter window. After a restart everything is showing as it should. Great work and thanks for the updates.
![test results2](https://user-images.githubusercontent.com/15352487/121221626-c05b9400-c853-11eb-8306-277771ff1440.PNG)

**Comment by FrankieCheese** [comment]
Everything is showing up for my as well.  Thanks for the quick fix!

**Comment by MrPig91** [comment]
@sk00t3r  thank you for the all the testing and confirmation on the version picking the RAID and no letter drives. Thank you everyone else for reporting this issue and giving me feedback.
