### ISSUE TITLE
Temp2 directory enhancement

### ISSUE THREAD

**Issue by toto99303** [MrPig91/PSChiaPlotter#61]
Hello, your work is greatly appreciated!
I would like to recommend adding Temp2 directory to the plotting options as a lot of people including me are using it heavily.
What it does is for Phase 3 it copies temp files to different temp directory (can be your destination dir or another SSD) and this essentially offloads your NVMEs from wearing and also allows you to stagger for example 4 jobs on 1TB drive with less time in between. Thanks again for your work and sharing with the community!

**Comment by MrPig91** [comment]
I will add this to the roadmap. Thank you for the suggestion!

**Comment by hero887** [comment]
How do we take advantage of this 2nd temp dir for phase 3? Do we just add a second temp dir in the dropdown and it automatically moves the temp plots to the 2nd dir? Something in the wiki would be helpful!

Great code so far! Really helps!

**Comment by MrPig91** [comment]
2nd Temp dir has now been added. The temp drives in the listbox are all for phase 1. This feature is in version 1.0.32. A lot was added to this update so please report any issues that you come across. Thank you :)
