### ISSUE TITLE
Compatability with mounted NTFS folders

### ISSUE THREAD

**Issue by OhNOherewegoagain** [MrPig91/PSChiaPlotter#62]
I ran out of drive letters and had to mount my drives as an empty NTFS folders, the GUI doesnt see the drive and if I select an NTFS folder(drive) i can not select the same disk for a second time, so there is no way for me to plot on the ntfs folder and the drive where the folder is mounted to. 

P.S: Great work! thanks you!

**Comment by sk00t3r** [comment]
You should not need a drive letter. Create an empty folder on a drive that currently has a drive letter. Open File Explorer, right click "This PC" then click "Manage". Navigate to "Disk Management" on the left then find your drive and right click on it. Select "Change Drive Letter and Paths..." then click "Add..." then select the radius button that says "Mount in the following empty NTFS folder:" Browse to the folder you created and that should set the mount point. Inside the Plotter make sure you use the path to the folder you created and it will write all the data to the drive that you do not have a letter for.

**Comment by MrPig91** [comment]
I will try to add no drive volumes in the next update. Thank you for submitting this issue.

**Comment by MrPig91** [comment]
@OhNOherewegoagain I have added the ability to see volumes without drive letters. Thank you for this feedback. The drive letter for the volume will appear as ?, but you should be able to distinguish them based on the other info.
