### ISSUE TITLE
I want to change the gui language，pls tell me where is the installed loaction

### ISSUE THREAD

**Issue by xiaoluoabc123** [MrPig91/PSChiaPlotter#64]
I want to change the gui language，pls tell me where is the installed loaction， otherwise，if we have another way to install pschiaplotter？

**Comment by MrPig91** [comment]
The module will be saved in the following location if installed via an Admin console. 
C:\Program Files\WindowsPowerShell\Modules\PSChiaPlotter

I am really sorry, but I do not have any plans to this module in a different language at the moment. Feel free to fork the repo and change the language as you see fit though.
