### ISSUE TITLE
About GUI

### ISSUE THREAD

**Issue by Lc001tr** [MrPig91/PSChiaPlotter#65]
MR pig great gui. But these are issues ;
1- If you use dynamic disk and not basic disk (I use dynamic disk ability of windows to easily concatenate 2 ssds for bigger size) your GUI's hdd side display cant show dynamic disks. 
2- cant change windows parts (job queue) sizes. It would be good to change all partial sizes.
3-pause all button would be nice. (sometimes it pauses wrong queue btw, I guess its because of scroll position or something)

**Comment by MrPig91** [comment]
I do not plan to add Dynamic disks after reading up how to find them with powershell since everywhere I read said not to use dynamic disks and to use storage pools instead. This is because Dynamic disks have been deprecated since 2000 form what I read. I will look into adding a pause all button.

**Comment by Lc001tr** [comment]
Thank you for fast update. 
For the dynamic disk, (I floowed also other topic) Maybe you can just put a free field which we can just enter the path of the drive. Because normally we use dynamic drive from the startchiaparalelplotting just with entering path. 
So maybe you can just put a free path field in the Drive selection box, and when we select that one, we can just write and add path down there. like "x:\chiatemp", at the moment if we select another drive we cant change drive letters path. maybe with the disable paralel button you can bypass also paralel & drive letter path selection.

**Comment by MrPig91** [comment]
You can now minimize each group box using the checkbox by the group box name. I added a Pause all button. This feature had a bunch of other updates so please report any issues you come across. Also I added basic directory setting to allow for manual input of the directories. All this in version 1.0.32+
