### ISSUE TITLE
No more than 9 jobs starts

### ISSUE THREAD

**Issue by OhNOherewegoagain** [MrPig91/PSChiaPlotter#67]
I listed 3 final drives and 3 temp drives 1tb each, so my setting were 144 total plots, 12 plots in parralel, delay 35min, RAM 4000, and 8 threads each(may be i dont need that much). The problem is that after the 8th queue was running for 1:35min no more queues were started, some time later i check and finally the 9th job has started. but now 12 hours has passed and the queues 10, 11, 12 are listed as running in "Jobs queues" but in Queued Plots they are not listed.

**Comment by MrPig91** [comment]
Sorry about this, I put the max number of runspaces at 10 during my testing, but meant to change to be dynamically assigned based on processor count. This will be fixed in the next release.

**Comment by Lc001tr** [comment]
Please if you put a limitter (cpu ram etc) put also bypass button for it. On servers like 2019 Cpu's are not workıng like you aspect and you shouldn't limit that way for better production.
Waiting with hurry :=)

**Comment by OhNOherewegoagain** [comment]
So theoretically if i spawn two jobs with 6 queues each it should work? or is it the total number of plots parallel that is limited?

**Comment by MrPig91** [comment]
I have fixed the hard coded limit on runspaces so you should not be limit to the number of queues you have. I am sorry that I missed that on initial release. I have also added some other features, and removed the limit on the RAM. Please open up a new issue is new problems arise from this release. I really changed more than I should in one release but there was a lot of feedback that I wanted to address.
