### ISSUE TITLE
the final drivers can't use mapping driver

### ISSUE THREAD

**Issue by tiyo** [MrPig91/PSChiaPlotter#70]
?

**Comment by MrPig91** [comment]
Can you expand on this, I am not 100% sure what you mean exactly.

**Comment by tiyo** [comment]
> Can you expand on this, I am not 100% sure what you mean exactly.

Unable to use network driver

**Comment by moonpo** [comment]
We cannot use neither a shared drive like \\192.168.10.XX\  will be good if we can input it manually

**Comment by MrPig91** [comment]
Network drives should be available, I do plan to add a manual way to input it in a future update though. Another person had a similar issue, but was able to resolve with the following command
`net use O: \server\share`
Except, use your driveletter and server.
Was mentioned in a closed issue.
vhttps://github.com/MrPig91/PSChiaPlotter/issues/63

**Comment by tiyo** [comment]
> Network drives should be available, I do plan to add a manual way to input it in a future update though. Another person had a similar issue, but was able to resolve with the following command
> `net use O: \server\share`
> Except, use your driveletter and server.
> Was mentioned in a closed issue.
> vhttps://github.com/[/issues/63](https://github.com/MrPig91/PSChiaPlotter/issues/63)

thx
