### ISSUE TITLE
Parallel processes limited

### ISSUE THREAD

**Issue by PlotNoob** [MrPig91/PSChiaPlotter#71]
Hello--I asked for 21 parallel plots, 63 total, with delay of 30:
![image](https://user-images.githubusercontent.com/85456572/121198796-07d42700-c838-11eb-9849-aa01d9495c15.png)

What I got was 9 parallel plots at most, but even for the 9 that I got, the delay times were off (all over the map):
![image](https://user-images.githubusercontent.com/85456572/121199448-8cbf4080-c838-11eb-91b0-66af3241e214.png)

Here is what shows under Job Queues:
![image](https://user-images.githubusercontent.com/85456572/121199532-a19bd400-c838-11eb-8fde-a58d4c59a81f.png)
![image](https://user-images.githubusercontent.com/85456572/121199601-afe9f000-c838-11eb-89c0-df2b76ba552f.png)
![image](https://user-images.githubusercontent.com/85456572/121199689-c09a6600-c838-11eb-8ee7-4b7442b6c0e7.png)
![image](https://user-images.githubusercontent.com/85456572/121199735-c8f2a100-c838-11eb-87e5-dfe7f21573f2.png)
![image](https://user-images.githubusercontent.com/85456572/121199780-d27c0900-c838-11eb-88a5-c80daa31c4c4.png)
![image](https://user-images.githubusercontent.com/85456572/121199804-d871ea00-c838-11eb-889e-79a343e44d5a.png)

Here is the most telling information--Looks like it started 8 successfully, and only started a ninth parallel plot much later, and that's about it:
![image](https://user-images.githubusercontent.com/85456572/121201884-7b773380-c83a-11eb-9468-95f9d8c63ab0.png)

NOTE: I had the same issue yesterday and tried to restart everything with some different settings and had the same result, but one difference--yesterday it was limited to 7, looks like today it was able to get up to 9 (but there was a long delay after the 7th plot and an even longer delay after the 8th plot). Please and thank you!

**Comment by MrPig91** [comment]
So looking at the GUI screenshots it appears this is not the latest version, because the latest version has "Job Name" column added. If you did update to version 1.0.28, did you close out of powershell and re-open it? Because it might have still used the older module if you used the same session after updating.

**Comment by MrPig91** [comment]
Thank you for the detailed explanation and the screenshots by the way, was very help to see what you meant.

**Comment by PlotNoob** [comment]
> So looking at the GUI screenshots it appears this is not the latest version, because the latest version has "Job Name" column added. If you did update to version 1.0.28, did you close out of powershell and re-open it? Because it might have still used the older module if you used the same session after updating.

Hi there! Is there anyway for me to pause the processes, update/restart the GUI, and continue those processes?

**Comment by MrPig91** [comment]
Not currently, I am sorry. I do want to look into adding that feature in the future though. If you don't want to cancel those plots it might be best pausing all the queues and waiting for the chia processes to finish maybe.

**Comment by PlotNoob** [comment]
That's what I have done. I then queued up some plots in the Chia Blockchain GUI that will take over for part of the day and then I will transition back again.

So, in your view, do you think the update should fix this?

**Comment by MrPig91** [comment]
The update should 100% fix it. I really dropped the ball and forgot to have the max runspaces for the runspacepool to be calculated by CPU threads. I had it hard coded at 10 when I was first writing the application and I meant to change it, but long forgot i hard coded it. Each job requires a runspace until it spawns all its queues, and then each queue has its own runspace and the UI requires its own runspace as well. So you have 2 jobs and 7 queues plus the GUI adds up to the hard coded 10.

**Comment by PlotNoob** [comment]
Wow! I can't thank you enough. Your promptness and support has been astounding.

**Comment by MrPig91** [comment]
Glad I could help. I think the main issue has been addressed so I will be closing this issue. Thank you for your feedback and help.

**Comment by PlotNoob** [comment]
The main issue was addressed.

Question: just to make sure, is there any strong reason not to use two
separate instances of this GUI? other than the obvious (like max parallel
will not detect parallel plots I'm the other gui--i already verified that).

Michael Shpunt
