### ISSUE TITLE
Keep having errors popup saying it cannot find the temp file

### ISSUE THREAD

**Issue by mikeydell** [MrPig91/PSChiaPlotter#74]
Not quite sure what to make of it, the plotter at about 10% starts popping up messages that the temp files cannot be found. I looked in the temp drives and the its filled with the temp files as its supposed to be. Maybe a bug?

**Comment by MrPig91** [comment]
Sounds like a bug to me. Could you post a screenshot of the message it is giving you?

**Comment by mikeydell** [comment]
I've updated and restarted the plotter, I'll keep and eye on it today and see if the error comes back again, if so this time I'll actually remember to screenshot like I should have done the first time.

**Comment by MrPig91** [comment]
Sounds good, I am sorry you ran into a bug with the app. I wish I knew why you were getting that message, but Ijust can't seem to find where that message would be coming from.

**Comment by mikeydell** [comment]
I'm starting to think my error was somehow related to the bug posted here, https://github.com/MrPig91/PSChiaPlotter/issues/55
Although I am not using raid, I did manually input the folder after choosing the drive, Today I changed it up a bit and just deleted the folders inside the drives and now just writing temp files to the drives directly such as E:/ and now the errors are gone for now.

**Comment by Jaga-Telesin** [comment]
Sounds like it could also be a permissions error, if it was related to a subfolder.

**Comment by mikeydell** [comment]
Yes I believe you are correct, so far the plots are at 15% and I haven't had any issues now that I'm writing the plots directly to the drive instead of drive/subfolder

**Comment by Jaga-Telesin** [comment]
On my plotter directories (I create them just under the drive root), I set Full Control permissions for my user account, and all Administrator accounts.  In case you want to revert back to folders and attempt it again.

**Comment by MrPig91** [comment]
It seem like it is working now. Feel free to re-open this issue if the error comes back.
