### ISSUE TITLE
NVME Windows raid is not visible and network drives too :-/

### ISSUE THREAD

**Issue by havranec** [MrPig91/PSChiaPlotter#77]
Hi i try pschiaplotter but my local nvme stripe is not visible in gui and network drives too ... :-/ it is possible add features for add disk letter manualy ?

Thank you Mirek

![c1](https://user-images.githubusercontent.com/85606960/121307032-d3c43900-c8ff-11eb-8c68-a0761120dc54.png)
![c2](https://user-images.githubusercontent.com/85606960/121307036-d3c43900-c8ff-11eb-9d66-eaf96d15b0b7.png)

**Comment by Exzellenz** [comment]
Hi i was experiencing the same when i ran the powershell as admin. 
once i  took the  the normal user all drives showed up.

**Comment by MrPig91** [comment]
@havranec is the your striped NVMe created with as a dynamic disk or a storage pool? Also as @Exzellenz correctly pointed out, running powershell as admin might not show mapped network drives since those are mapped to a user and if you are running it as a different user then it will not pick them up.

**Comment by havranec** [comment]
> @havranec is the your striped NVMe created with as a dynamic disk or a storage pool? Also as @Exzellenz correctly pointed out, running powershell as admin might not show mapped network drives since those are mapped to a user and if you are running it as a different user then it will not pick them up.

Hi @MrPig91 and @Exzellenz, thank you much for answer ... Tip from @Exzellenz resolve the problem with network drive, but NVME stripe set is not visible too. It is dynamic disk type with stripe.

![c3](https://user-images.githubusercontent.com/85606960/121489315-43a3f380-c9d4-11eb-93e4-0801c335916f.png)

Thanks !

Mirek

**Comment by spazhead13** [comment]
if you share the Raid0(stripped) drive in windows and then map it the program will recognize it.

**Comment by sk00t3r** [comment]
@havranec Unfortunately Dynamic Disks have not been supported my Microsoft for many many years. You should use Storage Spaces, set up a pool and then create your raid from there.

**Comment by MrPig91** [comment]
Glad you found a workaround for this issue. Sorry I don't support dynamic disks directly but I think it is reasonable given that are deprecated. Thank you :)
