### ISSUE TITLE
Get-ChiaMaxParallelCount says I have 3 TB of total SSD space but that's incorrect 

### ISSUE THREAD

**Issue by TropicalBlueLion** [MrPig91/PSChiaPlotter#8]
hey I only have a 2TB NVMe and a 250GB SSD. When I do Get-ChiaMaxParallelCount it Says I have a 3 TB SSD. Also it says I can do 8 plots in parallel because of the extra space but I can only do 7 in parallel. SSD = C, Q
![powershell_3ez2PVx4Sz](https://user-images.githubusercontent.com/83622453/116952082-c6a89000-ac57-11eb-992a-590db1927c52.png)

**Comment by MrPig91** [comment]
I am working on revising the output and code to make more clear. Thank you for bringing this to my attention!
