### ISSUE TITLE
First Delay label and Max Time input

### ISSUE THREAD

**Issue by hbapps20** [MrPig91/PSChiaPlotter#80]
Hi!

Thanks for this excelent tool, I'm just writing this because I saw some issues when creating a New Job

The label First Delay (min), it is not working with minutes but with seconds, so it es kind of confusing the lable.

Also, the max limit is something above 32000, as it is for seconds it is not possible to do a first delay for above 8 hours more or less.

Thanks!

**Comment by MrPig91** [comment]
Hi there!
Can I ask which version you are using. I believe I resolve this issue in a later update. You can check your version with the following command. The latest version is 1.0.29

`Import-Module PSChiaPlotter; Get-Module PSChiaPlotter`

**Comment by hbapps20** [comment]
Oh! Thanks,

I have 1.0.24, I just need to run Update-Module PSChiaPlotter?, and then make some tests.

If I update it will stop my current plotting?

Thanks!

**Comment by MrPig91** [comment]
You can open up a new admin powershell window and run Update-Module PSChiaPlotter and it "should" not mess with your current running GUI. But if you want to be safe you can wait until those are done and then update.

**Comment by MrPig91** [comment]
I think updating resolved the bug in a previous version. Thank you.

**Comment by hbapps20** [comment]
It works when updating! Thanks!
