### ISSUE TITLE
BUG: Pausing only work while ran as admin

### ISSUE THREAD

**Issue by AK1244** [MrPig91/PSChiaPlotter#84]
Pausing doesn't work for me while ran normally it just says "Running - Pending pause" and it sits there forever. I tried it on plots at many different phases and tried them overnight. I woke up and it still said pending pause. When I run it as admin it works fine. I'm not super code-savvy so I wouldn't know a fix or cause but thought I'd let you know.

**Comment by MrPig91** [comment]
So the pause will pause the queue and will let the current chia process to run until it is finished. Currently there is not way to pause the actual chia process so the queue must wait for the current chia process to finish and then it will prevent a new from starting if that makes sense. You can test this by clicking pause on a queue and then ending that queues chia process and it should go to pause after 10-20 seconds.

**Comment by AK1244** [comment]
Ahh, that makes more sense. Ill close this sorry
