### ISSUE TITLE
Enhancement: Ability to remove Jobs and to save last settings

### ISSUE THREAD

**Issue by pecprogramista** [MrPig91/PSChiaPlotter#87]
Hey!

1. I think it would be much easier to use the tool if it would be possible to **save jobs** with their settings so you don't have to put in all the details again every time you reopen **PSChiaPlotter**.

2. Also in case of a mistake it is **impossible** to completely delete a job. You have to **restart** a program to get rid of it.

Thank you!
Mateusz from Poland!

**Comment by Jaga-Telesin** [comment]
Save Job Profiles (multiple defaults) requested here:  https://github.com/MrPig91/PSChiaPlotter/issues/78

Would be nice to remove/pause a job, but that's probably on the 'future features radar'.  :)

**Comment by MrPig91** [comment]
Stopping Jobs will be on the next release. Along with a pause all button. Currently you can pause each queue a job starts, but that is not quite enough. Job profiles will also be on a future release, maybe not the next one though.

**Comment by pecprogramista** [comment]
Thank you!

**Comment by pecprogramista** [comment]
Yet its not especially about stopping jobs but removing/editing them :D

**Comment by MrPig91** [comment]
Quitting jobs and saving jobs have now been added to version 1.0.32. A lot was added to this update so please report any bugs that you may come across. Thank you :)

**Comment by MrPig91** [comment]
Version 1.0.33 should be the version to update to. Version 1.0.32 had a mistake and was not checking freespace.
