### ISSUE TITLE
Plots stuck at 98% 

### ISSUE THREAD

**Issue by lenith** [MrPig91/PSChiaPlotter#88]
I'm think this issue has nothing with PSChiaPlotter, however wondering what could be safe escape from this situation. 4 plots stuck on 98%, rest three approaching 98%. I can see *. tmp files in both temp and final directory each with 106 GiB in size. This situation arrives after plotter successfully completed 5 plots. Unless they are moved to final directory, plotter wouldn't add new files to plot. 

Last line of Logs of these plots shows: Final file size 101.357 GiB

Does 98% in PSChiaPlotter is same as 100% shown in official plotter? Asking it because sometime it stucjs at 100% in official plotter and needs manually renaming the plot.

**Comment by Jaga-Telesin** [comment]
At 98% the chia.exe process is copying the file to the destination drive.  Is your destination drive full?  Accessible via the network?  Correct write permissions?

Also if it's across the network, even a 1Gbit network takes ~15 minutes to copy *each* plot file, and if you have more than one copying at once it congests the network quite a bit, making the cumulative time even longer than 15m/per.

I've never had one faily to copy with PSChiaPlotter, and I've not had one stuck at 100% in the official plotter needing renaming.  You may have permissions issues on your rig(s).

**Comment by lenith** [comment]
It's not a permission issue because 5 plots have already moved by PSCP without any issue, though I think there is something with the drive as it happens only with this one. It's external 5 tb drive connected directly to main node through usb 3.0 hub. I think kill process would not help here as it will delete tmp files. May be I can wait till all running plots reaches 98% now then try manually to rename atleast one of them to see if that appears valid in official farmer.

**Comment by Jaga-Telesin** [comment]
If your destination was the same as the successfully copied plots, then yes - it isn't a permissions issue.  That's the good news.

Does the Windows Task Manager/Performance show any activity on that destination drive?  Did the drive sleep between copies?  Is USB allowed to selectively suspend the USB 3.0 hub?  Has the drive ever gone offline before you started Chia plotting?

I'd check drive activity first thing, see if it has anything going on.  And then I'd look at SMART data for the drive, see if any categories show warnings (like reallocated sectors).  The drive may be trying to accept the writes, but failing due to escalating failures on sectors.

Lots of things that could be affecting it here.

**Comment by lenith** [comment]
Thank you, those suggestions opens up some clues I think. I checked the drive activity and it's 100%. Writing speed shows between 15-40 MB/s. Does that mean I just have to wait and it's going to take hours. Is that it?

CrystaldiskInfo showing health status good. I don't understand much of those parameters numbers showing in CrystaldiskInfo but all are flagged blue that, I assume, is good.

**Comment by Jaga-Telesin** [comment]
If it's a 5400 or 7200 RPM drive, the lower write speed means it's probably writing multiple Plot files at the same time.  Normal speeds on a SATA drive are between 90 and 150 MB/s.  You may have two, or even three copies going to the drive at the same time, which on a USB connected drive (that does transaction handshaking constantly), means it'll be another hour or more before they are done.

**Comment by pecprogramista** [comment]
if someone still uses 1g connection for file transfer I strongly reccomend investing 30$ into [hp nc523sfp 2x10Gbit sfp+](https://techbuyer.gumlet.io/media/catalog/product/cache/f0dc0c2dab61c903f8926159ad53b679/5/9/593717-b21-hp_hp_10gb_2port_network_card_8_9.jpg) network card :)
