### ISSUE TITLE
Helpful Tips List

### ISSUE THREAD

**Issue by spazhead13** [MrPig91/PSChiaPlotter#89]
if you want to use windows Dynamic drives,  just share them with a new drive letter, than PSChiaPlotter will recognize it in the temp selection

**Comment by spazhead13** [comment]
if you have 1TB SSD/NVME drive, you can only plot 3 limit, and the ignore Max PLot button does not appear,
what i did to fix this was to create a windows span drive and add a older 120GB to the end of your 1TB SSD.
then share & map the drive as mentioned above.
that way  PSChiaPlotter see's the drive as 1.12 TB and allows 4 plots Max!

**Comment by pecprogramista** [comment]
If you still cannot see your Raid drives after all the updates, just create a folder on any other drive and symlink your Raid drive to this folder :)

**Comment by MrPig91** [comment]
I have also added an "Basic Plotting" setting so you can now enter the file path manually instead of using the drop down. :)
