### ISSUE TITLE
Get-ChiaPlottingStatistic not process all logs files from a network share

### ISSUE THREAD

**Issue by pipone** [MrPig91/PSChiaPlotter#93]
I have a Win10 box which access to linux shared plot-log folders (via samba)

When I run:

` Get-ChiaPlottingStatistic -Path:w:\*.log`

I get statistics only of the newer log file (only 1 file is processed)

Is there any permissions to set regarding accesing network shares? 

Thanks!

**Comment by pipone** [comment]
`PS V:\> Get-ChiaPlottingStatistic -Path:v:\*

KSize RAM   Threads Phase 1     Phase 2     Phase 3     Phase 4     Total Plot  Plot And Copy Time Copy Time   Temp  Final
                                                                    Time                                                  
----- ---   ------- -------     -------     -------     -------     ----------- ------------------ ---------   ----  -----
32    3389  2       4.12 hrs    1.66 hrs    3.59 hrs    13.97 mins  9.21 hrs    9.43 hrs           13.57 mins  /m... /p...



PS V:\> (Get-ChildItem | Measure-Object).Count
167

PS V:\> `

**Comment by MrPig91** [comment]
Try running the following 
`Get-ChiaPlottingStatistic -Path (Get-ChildItem -Path w:\*.log).FullName`

**Comment by MrPig91** [comment]
I plan to add ValueFromPiple so you can run this in the future
`Get-ChildItem -Path w:\*.log | Get-ChiaPlottingStatistic`

**Comment by pipone** [comment]
> Get-ChiaPlottingStatistic -Path (Get-ChildItem -Path w:\*.log).FullName

That did the trick!!! 
I am so newbie with Powershell  :(  

Thanks a lot!!!

**Comment by MrPig91** [comment]
Glad a could help :)

**Comment by pipone** [comment]
The pipe would be a nice adding!
Maybe I could mix two paths as Get-ChiaPlottingStatistic input.
Awesome job!
