### ISSUE TITLE
hi ,only support for k32?

### ISSUE THREAD

**Issue by xiaoluoabc123** [MrPig91/PSChiaPlotter#94]

**Comment by xiaoluoabc123** [comment]
only support for k32?, i can't change the k-size,pls help me

**Comment by MrPig91** [comment]
This will be available on the next release. Hopefully today if time permits.

**Comment by xiaoluoabc123** [comment]
thanks very much，barvo

**Comment by MrPig91** [comment]
Took much longer than expected yesterday. Things never work out as I expect. The new version has been release and you can now plot with different KSizes. Please note, I added a lot in this update so if you do run across any bugs please create a new issue. Thank you.

**Comment by MrPig91** [comment]
Version 1.0.33 should be the version to update to. Version 1.0.32 had a mistake and was not checking freespace.
