### ISSUE TITLE
Disque SAS RAID 0

### ISSUE THREAD

**Issue by Sky1414** [MrPig91/PSChiaPlotter#96]
Hello,
My SAS disk in aggregate (RAID0, dynamic disk) is not recognized (CHIA sees it)
![Sans titre](https://user-images.githubusercontent.com/83701847/121790013-3573f400-cbdb-11eb-859d-9a09d3ed1966.jpg)

**Comment by sk00t3r** [comment]
It is because it is a dynamic disk and Microsoft has not supported dynamic disks in a very long time. You have two options. Convert them Basic and if you need them to be in a raid use Storage Spaces (really the correct way), or share out your dynamic disk and map it to the computer (workaround).

**Comment by Sky1414** [comment]
And  do not support network disk for destiniation :  "Failed To Grab Volume Info"
Thank you for your attention

**Comment by sk00t3r** [comment]
Did you map the network drive? 

What do you get if you run this command?
```
Get-CimInstance -ClassName Win32_MappedLogicalDisk | Select-Object -Property Name, ProviderName, VolumeName, FileSystem
```
I see by your screen grab that you have the latest update and network drives do work. You can right click on "This PC" inside file explorer and click "Map network drive" or you can do the same thing using PowerShell with the following command:
```
New-PSDrive -Name "DriveLetter" -PSProvider "FileSystem" -Root "\\server\share" -Persist
```
I have attached a picture of one of my setups and you can see that the destination (final dir) is my "W:\" drive and that it is a network disk.

![network final drive](https://user-images.githubusercontent.com/15352487/121808407-53b31180-cc26-11eb-8a12-ad480f79e665.PNG)

**Comment by Sky1414** [comment]
Hello,
I partially solved the problem:
If I create a job in "Basic", it's OK
If I switch to advanced this problem is back 'Waiting on temp space'
[Bug.xlsx](https://github.com/MrPig91/PSChiaPlotter/files/6644685/Bug.xlsx)

**Comment by sk00t3r** [comment]
It is a very bad idea to use you OS drive as your temporary plotting drive. I highly recommend against this. The reason you do not get the "Waiting on temp space" problem when you use Basic Mode is (from what I just read) it does NOT do any space checks. Advanced Mode makes sure everything is OK before starting. Your problem is that you do not have enough free disk space on you temporary plotting drive. Again I can not stress enough that it is a terrible idea to plot on your OS disk.

**Comment by Sky1414** [comment]
The problem of the "invisible" disk in aggrega is also corrected with the use of the basic version
The use of disk C was temporary pending a RAID 4 x 600GB disk
Thank-you for your prompt response
![image](https://user-images.githubusercontent.com/83701847/121822992-a7634080-cca2-11eb-90e9-5204f0d25ecb.png)
![image](https://user-images.githubusercontent.com/83701847/121823066-1771c680-cca3-11eb-9642-b0aac1abd156.png)

**Comment by sk00t3r** [comment]
If you look at your first screen capture your "I:\" drive is setup as a "Dynamic" disk. If you don't have any important data you can open up disk management and right click on that drive and click delete volume. Then right click and create a new volume, give it the same drive letter and make sure it says "Basic" on the left hand side when you are done. 

This will delete all your data so only do this if you can move your data or you don't have any data on that disk.

**Comment by Jacek-ghub** [comment]
> If you look at your first screen capture your "I:" drive is setup as a "Dynamic" disk.

I don't this that you can convert RAID to Basic.  I tried to do that, but didn't see an option for it.  Unless, you kill that RAID array, and format each disk individually.

I guess, those are just work arounds for Get-ChiaMaxParallelCount/Get-ChiaVolume functions not really trying to also discover dynamic/RAID disks (those are not listed, if searching for physical drives).

**Comment by Jacek-ghub** [comment]
@Sky1414 If you map your RAID with:

> net use z: \\localhost\i$\path

where "i$" means you "i:" RAID array, you can use that RAID array in Advanced section as well (at least it started for me).  Although, my pSChiaPlotter is v. 1.0.40, so maybe you need to update yours.
