### ISSUE TITLE
Cannot call method on a null value?

### ISSUE THREAD

**Issue by mikeydell** [MrPig91/PSChiaPlotter#97]
Hello,
Not sure what I'm running up against here, currently my chia plotter has 8 individual drives for plotting. But anytime I try to go past 6 simultaneous jobs I get a popup with the message "cannot call method on a null value" I've looked in the app trying to see if I am missing a setting for max jobs but I'm not seeing anything.
![screen2](https://user-images.githubusercontent.com/85267042/121793596-3a7a7880-cbc6-11eb-9211-cfc9c85a187d.png)

**Comment by mikeydell** [comment]
I'm also including a screenshot of my system specs, as I don't believe it's related to my systems ability but who knows?
![screen3](https://user-images.githubusercontent.com/85267042/121793632-aa88fe80-cbc6-11eb-839d-06b7b43e8fef.png)

**Comment by sk00t3r** [comment]
I think you would benefit from creating a storage pool with your 6 sas drives (or better yet if you have a raid card) and set them up in a raid 0 config. This would give you ~1.8TB and 6x read and write speed gain. This would also help with parallel plotting and queue delay. Would more than likely see an increase in plots per day.

As for the error I am not 100% sure but I don't think you have enough free space on G:, H:, E:, & F: for the temporary files. Run time is only a few minutes and your free space is under 120GB.

**Comment by phpfrog** [comment]
> As for the error I am not 100% sure but I don't think you have enough free space on G:, H:, E:, & F: for the temporary files. Run time is only a few minutes and your free space is under 120GB.

I agree, doesn't look like enough space on the drives. It at least fits the code criteria where it errors.

**Comment by mikeydell** [comment]
> I think you would benefit from creating a storage pool with your 8 sas drives (or better yet if you have a raid card) and set them up in a raid 0 config. This would give you ~2.4TB and 8x read and write speed gain. This would also help with parallel plotting and queue delay. Would more than likely see an increase in plots per day.
> 
> As for the error I am not 100% sure but I don't think you have enough free space on G:, H:, E:, & F: for the temporary files. Run time is only a few minutes and your free space is under 120GB.
> 
> It looks like you tried to start 8 jobs at the same time with 4 threads each, You only have a total of 32 threads not sure if this would have any impact or not but its usually not good to leave nothing left for other OS functions. Although when I "over-provision" my threads it does not seem to much care.
> 
> I also can not replicate the issue that you are seeing at 6 current runs. What is the status of your other jobs (the ones after 6) in the "Job Queues"?
> ![queue-1](https://user-images.githubusercontent.com/15352487/121795789-f85f3000-cbe1-11eb-931f-90d0dc424994.PNG)

I will try putting all the drives into raid 0 as you suggested, I'm still quite new to Chia plotting so learning on the fly lol. I was watching some videos on youtube that suggested this config I'm using now but it seems quite slow as you have pointed out. Monday I'm adding two nvme drives into the config so I'm hoping that speeds the process up. As for drive space what happened was I paused the plots and tried creating a new job to get the error for the screen shot, looking back I think what happened is I possibly chose the same drive twice in a row without realizing it and  that is what caused the error,
