### ISSUE TITLE
Antivirus problem (Bitdefender)

### ISSUE THREAD

**Issue by kszabok** [MrPig91/PSChiaPlotter#98]
Hello.

I wanted to see Log Stats. First time was no problem, but in second time my Bitdefender antivirus made an alarm, and it closed everything, and it wanted to move all temporary plot file to quarantine. Is it a specific Bitdefender problem? Has anyone else complained about this problem? I made some exclude, but it was not help.

![malware_alarm](https://user-images.githubusercontent.com/84275629/121815603-9bae5480-cc77-11eb-8e5e-8a17bfb5024d.png)

**Comment by MrPig91** [comment]
This is the first time it has been reported. I do not use BitDenfender so I am not sure the best way to bypass it. You can try using the "-NoNewWindow" switch to see if that helps. I use this switch for testing only, but it might help you. Drawbacks are that it will not create a log file, if you close the powershell window that you launch the GUI from it will also close the GUI and logs will written to the powershell window that you launched the GUI from.

**Comment by sk00t3r** [comment]
@kszabok I don't use Bitdefender but I did find this on their support page and it may apply to your situation.

[How to add Antivirus exceptions](https://www.bitdefender.com/consumer/support/answer/13427/)

**Comment by kszabok** [comment]
I've made exceptions for chia.exe and powershell.exe, so it no longer alarms

**Comment by MrPig91** [comment]
That is good to hear. I am glad you got it working :)
